### ISSUE TITLE
Multiple occation of mutable default argument

### ISSUE THREAD

**Issue by sulyi** [yt-dlp/yt-dlp#1021]
## Checklist

- [ ] I'm reporting a bug unrelated to a specific site
- [x] I've verified that I'm running yt-dlp version **2021.09.02**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] The provided URLs do not contain any DRM to the best of my knowledge
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Description

It caught my attention, that there are numerous occasion of mutable default argument in function or method definition.
These can cause very nasty behaviour and generally needs to be avoided.

I'll try to collect and fix them later. Till then here are a couple of examples:
https://github.com/yt-dlp/yt-dlp/blob/7738bd32722154a26f70006e0fe586f40d06e606/yt_dlp/downloader/__init__.py#L10
https://github.com/yt-dlp/yt-dlp/blob/7738bd32722154a26f70006e0fe586f40d06e606/yt_dlp/extractor/adobepass.py#L1384
https://github.com/yt-dlp/yt-dlp/blob/7738bd32722154a26f70006e0fe586f40d06e606/yt_dlp/extractor/brightcove.py#L471
https://github.com/yt-dlp/yt-dlp/blob/7738bd32722154a26f70006e0fe586f40d06e606/yt_dlp/extractor/common.py#L654
https://github.com/yt-dlp/yt-dlp/blob/7738bd32722154a26f70006e0fe586f40d06e606/yt_dlp/extractor/common.py#L717
...
and not just dict, but lists also.

**Comment by pukkandan** [comment]
This is inherited code from youtube-dl. I was aware of the issue and have already fixed a few instances that were more problematic. These ones are currently not doing any harm. ofc, it is best to fix them anyway
