### ISSUE TITLE
Python3 runtime for macOS ?

### ISSUE THREAD

**Issue by section83** [yt-dlp/yt-dlp#1075]
## Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.09.25**
- [X] I've searched the bugtracker for similar feature requests including closed ones

## Description

All current installs of macOS currently include Python2.7.  Apple have advised that Python2.7 will be removed from a future release of macOS (but have not stated which/when). They advise that Python apps should be bundled with a Python runtime.

I have developed a [macOS applet](https://github.com/section83/MacYTDL/) which currently uses youtube-dl and will use yt-dlp in the next release.  I am looking at including a Python runtime for macOS users.  But, I don't want to do that if it will be provided with yt-dlp (as it is for Windows users).  Can/will a future release of yt-dlp for macOS include a Python3 runtime ?

**Comment by pukkandan** [comment]
I don't have any mac devices and so can't write/test code for this. If you can make a PR to create a bundle in the release process (build.yml), I can merge it

That said, yt-dlp doesn't use python2.7 anyway. We only support 3.6+. So I believe this is irrelevant for us?

**Comment by section83** [comment]
Many thanks, that will be good.

Although yt-dlp is built for Python3.6+, although I need to do more testing, I think it works acceptably with Python2.7.  If that is correct, there's no rush needed to prepare a runtime Python for macOS – it could be 12-24 months before Apple remove Python from macOS entirely.  Anyway, it will take me time to learn how to create a runtime !

Cheers.

**Comment by nao20010128nao** [comment]
yt-dlp now uses f-string (formatting string), so it won't work on 2.7 anymore. You will get SyntaxError when running.

**Comment by section83** [comment]
OK, thanks.  I'll speed up my research on how to create a Python runtime for macOS.

Cheers.

**Comment by section83** [comment]
I think I have created a Python3 runtime.  I could only find one guide on creating runtimes and it seems to result in a lot more guff than is needed.  **ALL** advice out there is designed for Python developers – none is designed to result in something for users.  I've reached out to the MacPython community but no responses as yet.

I have compressed it all into a set of Zip files (keeping within the 25MB GitHub limit).  If you can figure out what to do from here, great.  Otherwise, I'm happy to continue my research.

I also found a tool that supposedly turns a Python project into a macOS app. But, of course, I couldn't get it to work.

The files are here: https://github.com/section83/MacYTDL/tree/master/Components/Python3.8.

**Comment by pukkandan** [comment]
I thought you could use pyinstaller and that just some settings need to be tweaked https://pyinstaller.readthedocs.io/en/stable/usage.html#building-mac-os-x-app-bundles

**Comment by section83** [comment]
Thanks for that. 4 days of searching and reading and I had not seen pyinstaller.

The runtime I built yesterday was generic and seemed to include a lot of unnecessary files, from a user perspective.

My objective is to include the minimum to enable yt-dlp to work on a Mac.  I think that's important especially because Apple expect **every** Python app to include its own runtime.  They have provided no advice on where to store the runtimes.  I've found a few which are inside the app bundles but I bet that others will try to load into Library/Frameworks.  Users could end up with quite a large number of runtimes all slightly different and probably different versions.  I think Apple have forgotten what it's like to be a user trying to keep a handle on the thousands of files stored on their Macs.

Cheers.

**Comment by section83** [comment]
OK, I'm lost.  The PyInstaller doc says it is invoked by: pyinstaller myscript.py.  But, there is no file called yt-dlp.py.  So, I can't figure out which file to pass to pyinstaller.  Is it setup.py ?

Maybe if you can show me the command used to create the Windows EXE, I'll understand how this all works.

Thanks.

**Comment by pukkandan** [comment]
> OK, I'm lost. The PyInstaller doc says it is invoked by: pyinstaller myscript.py. But, there is no file called yt-dlp.py. So, I can't figure out which file to pass to pyinstaller. Is it setup.py ?

You need to point pyinstaller to `yt_dlp/__main__.py`. `setup.py` is for `pip install` and has nothing to do with the executable

> Maybe if you can show me the command used to create the Windows EXE, I'll understand how this all works.

`pyinst.py` is the script used to generate the windows executable. Most of it is concerned with setting the metadata correctly. The main code boils down to `pyinstaller --onefile yt_dlp/__main__.py`. You can try the same in mac. Maybe it will work?

**Comment by section83** [comment]
Ah, that's much better.  Result was a dist folder and executable named __main__ but, I guess I can fix that.  Anyway, tried the executable in Terminal and it worked.  I'm going to test on two more Macs (which don't have Python3).

At first, I'm sticking with the "one folder" implementation.  When I'm comfortable I'll try out the one file approach.  Then, I can decide which would be best.  I have an Apple Developer ID so, if necessary, I can code sign the process.

Cheers.

**Comment by section83** [comment]
Well that was satisfying.  Many thanks for steering me to pyinstaller and providing help.  I have working single folder and single file versions of yt-dlp.  The single file is only 7.6MB which is very liveable.  Both types run quite quickly (as fast as YTDL). The single file version does create a 10MB temp folder which is rm'd on exit.

I have tested yt-dlp in my MacYTDL applet and all I had to do was a search and replace in my code which is very nice.

Thank you for putting up with my beginner/numpty questions.  I'm going to focus on fine tuning and working out proper procedures for users to follow etc.  I also need to test on various Mac architectures and macOS versions.  I have a friend who can test on an M1 MacBook Air which will be important.

As far as YT-DLP is concerned, would it be best to use the most recent version of Python ? [version 3.9.7].

**Comment by pukkandan** [comment]
The windows executables use 3.8 for compatibility. I am not sure what such needs are for mac

>  I'm going to focus on fine tuning and working out proper procedures for users to follow etc.

If you can instead integrate the process into our build.yml, I would be glad to release it myself

**Comment by section83** [comment]
According to the Python3.9 installer it will work with macOS 10.9+.  10.9 was released in 2013 so, it's fairly old.  Apple's Xcode installs Python3.8 so, maybe we should stick with that.  I'll do some more background reading and let you know.

I'll also look at build.yml.

Cheers.

**Comment by pukkandan** [comment]
hm.. I just remembered something. The autoupdater will also need to be modified. Do you know whether mac exes can be replaced while it is running (like UNIX), or is it locked (like Windows)

**Comment by section83** [comment]
Don't know. I know an app cannot be trashed while it's running:

![Screen Shot 2021-09-30 at 8 34 19 pm](https://user-images.githubusercontent.com/7471595/135439823-a7dba097-4d6a-4c92-92f3-33b97793b633.png)

Also, they can't be replaced while running:

![Screen Shot 2021-09-30 at 8 37 50 pm](https://user-images.githubusercontent.com/7471595/135440294-25c58637-49ca-4bfd-87fb-7b1bb1685537.png)

So, probably the same applies to executables.  Yet, youtube-dl autoupdate works – although it has to be manually restarted:
```
~ % youtube-dl --update
Updating to version 2021.06.06 ...
Updated youtube-dl. Restart youtube-dl to use the new version.
```

Not so with YT-DLP:
```
~ % yt-dlp --update
Current Build Hash 5109928ae16dcaaae8360e59a2683bc858c3b302b111648efc787c8152aca1f9
ERROR: can't obtain versions info. Please try again later or Visit  https://github.com/yt-dlp/yt-dlp/releases/latest
```

**Comment by pukkandan** [comment]
> Not so with YT-DLP:

Is that the binary you made? or the one without python runtime?

> Yet, youtube-dl autoupdate works – although it has to be manually restarted:

Yes, the one without python runtime will work

**Comment by section83** [comment]
>Is that the binary you made? or the one without python runtime?

It was the binary without the runtime (I just downloaded it from the YT-DLP GitHub release).  This is what I got when I tried the YT-DLP that I built yesterday:

```
~ % yt-dlp-temp --update
Current Build Hash 8bc47f4428eb84db05c9bc98c97c03963ad560342c773c3722d07537c4fb4972
yt-dlp is up to date (2021.09.25)
```

Difficult to test fully as I would need to build it from old YT-DLP source.

**Comment by pukkandan** [comment]
> Difficult to test fully as I would need to build it from old YT-DLP source.

You can manually adjust the version number in `__version__.py` or download from the older releases

**Comment by section83** [comment]
> You can manually adjust the version number in __version__.py or download from the older releases 

Of course. I've DL'd yt-dlp-2021-09-02 and built a single file version.  I installed it in usr/local/bin and did the following:
```
sudo yt-dlp --update
Password:
Current Build Hash 332d15a0e98e2edd4c452ad865007fe88b7c1ad6ee267fea60d4ee767330acb3
Updating to version 2021.09.25 ...
Updated yt-dlp to version 2021.09.25
```
I had to "sudo" because users don't have write permission on that folder. Anyway, it looked OK but, I had to do a "chmod a+x" to make it executable.  And, when I tried running it, macOS then popped:

>zsh: exec format error: yt-dlp

Something must be amiss: after the update YT-DLP (2021-09-25) was 12MB in size (instead of 2MB).

**Comment by section83** [comment]
Here is the "warnings" file on the build:

[warn-__main__.txt](https://github.com/yt-dlp/yt-dlp/files/7270655/warn-__main__.txt)

I'm thinking of adding some modules to the build in particular: mutagen, pycryptodome, websockets, AtomicParsley and rtmpdump (altho it looks very old).  My MacYTDL applet has a copy of AtomicParsley in the bundle and it's an optional install which seems to work.  It's my own build from the 2014 source a few years ago but, I might change to the official GitHub "wez" release.

**Comment by section83** [comment]
G'day, me again.  I've looked through build.yml and done some background reading on Actions.  I have some suggestions which are in the attached file.  I think that building for macOS could be easier than Windows – to start, YT-DLP already works on macOS; it only needs a Python3 install.  But there are some differences in PyInstaller options and YML commands.

[Suggestions for Build.yml.rtfd.zip](https://github.com/yt-dlp/yt-dlp/files/7275710/Suggestions.for.Build.yml.rtfd.zip)

**Comment by section83** [comment]
> Please try to keep future conversations in the actual comments and use attachments sparingly.

I'm sorry. Message received.

>Once a minimum supported macOS version is decided, use the latest python that is supported by that

OK. That'll be Python 3.10.

>No. I will not release installers, only portable binaries

That's fine.

> As for the various architectures, if possible, we want to release only a single binary for all MacOS systems. So I guess universal it is. But honestly, I have no idea what is the difference b/w these or which of these PyInstaller supports.

Yes, a single binary is best.  A "Universal2" app contains both x86_64 and arm64 code. The relevant code runs according to the architecture of the Mac on which it runs.  Thus a single app can run on all Macs of either architecture.

PyInstaller can output binaries in Universal2.  I have tested that – it works.

> So you are going to have to make a PR for this

OK.  I don't yet know how to make a PR and how to use YAML.  So, I'll fork yt-dlp, do my research and test run ideas.

Many thanks for your help and all your efforts for yt-dlp.

**Comment by section83** [comment]
Many thanks to smplayer-dev and pukkandan for doing this macOS work.  Much appreciated.  It would have taken me more weeks to catch-up.

By the way, do you know why the Universal2 architecture didn't work ?  It's not critical but, eventually, Apple will deprecate Rosetta2 and so there will have to be either a Universal2 and/or arm64 version.

**Comment by pukkandan** [comment]
It does work. If you are testing locally, make sure your python is universal2

**Comment by section83** [comment]
I've spent all yesterday and today trying to test the macOS changes. I've tried hard but GitHub has been fighting me at every step.  I can't get the "build_unix" step to work.  The GitHub docs are too obtuse for me.  So, I give up.

What I've seen looks good – only question I have is use of the macOS-11 runner instead of macOS-10.15.   I'll wait until you've put out a new release to test the macOS executables.
