### ISSUE TITLE
Unable to use Python 3.9 if Python 3.8 is also installed, and default.

### ISSUE THREAD

**Issue by MarkJeronimus** [yt-dlp/yt-dlp#11506]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [ ] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [ ] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I'm on Mint 20.4, which _requires_ puthon3.8.10 to be aliased to `python3`. I installed Python 3.9 alongside it (from the main repositories) but it needs to be invoked using `python3.9`

I rebuild the `yt-dlp.sh` executable to change `python3` in the header to `python3.9`, and now it can run:

![image](https://github.com/user-attachments/assets/429caf69-6b1c-4433-ba97-8b40f6207f38)

I found the issue is possibly due to this line: https://github.com/yt-dlp/yt-dlp/blob/e398217aae19bb25f91797bfbe8a3243698d7f45/Makefile#L42 or to that line https://github.com/yt-dlp/yt-dlp/blob/e398217aae19bb25f91797bfbe8a3243698d7f45/Makefile#L99

Expected behavior
---
It (the executable, not makefile) looks for the newest python that is at least version 3.9

Actual behavior
---
It hardcodedly looks for `python3`, expecting it to be a symlink to Python 3.9 (which is often the case, in most Linux flavors that are not 3 years old)

Proposed fix
---
I'm not too familiar with sh scripts in general, let alone how zipped files are appended at the end, but I imagine some sh-scripting that looks for the newest python executable on the PATH that is at least version 3.9, then executes it with the (zipped?) main py file. It should avoid testing for specific hardcoded versions as this is fragile coding. (e.g., `python3.9` might not exist if 3.10 is installed.)

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ ~/Downloads/yt-dlp -f 18 https://www.youtube.com/watch?v=YrNIenrAZ-w
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/zom-b/Downloads/yt-dlp/__main__.py", line 14, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/home/zom-b/Downloads/yt-dlp/yt_dlp/__init__.py", line 4, in <module>
ImportError: You are using an unsupported version of Python. Only Python versions 3.9 and above are supported by yt-dlp

$ python --version; python3 --version; python3.9 --version
Python 3.8.10
Python 3.8.10
Python 3.9.5
```

**Comment by bashonly** [comment]
When making your own `yt-dlp`, you can override the Python path in the shebang via environment variable:

```
PYTHON="/usr/bin/env python3.9" make yt-dlp
```

`/usr/bin/env python3` is hardcoded in the Makefile for maximum compatibility. The fact of the matter is that the unix executable zip builds included with our github releases can't accommodate every system. This is why we also provide the release [tarball](https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp.tar.gz) which has everything you need to make your own executable zip build.

**Comment by MarkJeronimus** [comment]
I expect not everyone is savvy enough to build it using `make`, or willing to sort out dependencies (I have a bit of a `make` PTSD myself). Up till now I've just always downloaded the latest binary.

**Comment by Grub4K** [comment]
To expand upon the other answer: We cannot hardcode `3.9` as then other, more modern versions of python break (think systems that have `python3.10` or `python3.11` only).

Users (and you) can also do either of these (in order of preference):
- Install `yt-dlp` through `pipx`/`uv` or in a virtual environment
- Use `yt-dlp_linux`, which bundles its own python
- Alias `yt-dlp` to something that adds a `python3` into path thats symlinked to `python3.9`
```sh
mkdir -p ~/.local/bin/python/
ln -s /usr/bin/python3.9 ~/.local/bin/python/python3
alias yt-dlp='PATH="${HOME}/.local/bin/python:${PATH}" yt-dlp'
```

**Comment by bashonly** [comment]
It looks like this is what was happening in #11479 too, but I'd rather direct users experiencing the same problem to this issue instead, since it better describes what is happening

**Comment by dirkf** [comment]
You can also do `python3.9 path/to/yt-dlp args...`, or create an alias that does that.
