### ISSUE TITLE
Sign the Mac executive file in the release

### ISSUE THREAD

**Issue by aereobert** [yt-dlp/yt-dlp#11764]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Now the released executive for MacOS is unsigned, so it needs to be manually enabled in the security settings before being able to use.

Signing it would remove the warning. yt-dlp is now a big project and is worth to be signed :)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by seproDev** [comment]
There are two primary roadblocks for having signed macOS executables. From the technical side, signing needs to take place in the CI pipeline, as all yt-dlp releases are automated. Last time I looked in to it, this was a non-trivial problem.
From the administrative side, someone from the maintainer team needs to be willing to pay $100/year to Apple. And either have their name attached to the released binary or form an LLC/other company structure.

As far as I am aware, none of the maintainers are currently willing to pay Apple.
