### ISSUE TITLE
[Feature Request] Mention third party packages in readme

### ISSUE THREAD

**Issue by 3nt3** [yt-dlp/yt-dlp#1313]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running yt-dlp version **2021.10.10**
- [x] I've searched the bugtracker for similar feature requests including closed ones
- [x] I've read the opening an issue section in CONTRIBUTING.md
- [x] I have given an appropriate title to the issue

## Description

There is [an AUR package](https://aur.archlinux.org/packages/yt-dlp/) by `rumpelsepp`, who doesn't seem to have a GitHub accoount, or I would mention them. For the comfort of arch users maybe this package could be listed in the INSTALLATION section of the README.

**Comment by Ashish0804** [comment]
This is not maintained by any of the yt-dlp members and is out of our hands in regards of authenticity of the sw as well as version.
No need to add this to official readme imo.

**Comment by 3nt3** [comment]
ok, that seems fair and would also have been my biggest concern.

**Comment by pukkandan** [comment]
I never got around to writing a wiki. Instead, I have decided to crowd-source that job. [An empty wiki](https://github.com/yt-dlp/yt-dlp/wiki) has been created for the repo with it's source code mirrored to https://github.com/yt-dlp/yt-dlp-wiki. Anyone may open PRs to that repo to add content to it
