### ISSUE TITLE
Manpage: Autoconverted version contains unnecessary junk

### ISSUE THREAD

**Issue by hseg** [yt-dlp/yt-dlp#1448]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.10.22**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Some parts of `README.md` shouldn't be in the manpage:
(note: these probably should be added to `devscripts/prepare_manpage.py`)

- [ ] Badges are unnecessary and unreadable
- [ ] Description is missing header
- [ ] Table of contents unnecessary
- [ ] `NEW FEATURES`, `INSTALLATION` unnecessary
- [ ] Manpage conventions
  - [ ] Rename `USAGE AND OPTIONS` to `OPTIONS`
  - [ ] Replace tabular option documentation by
    ```
    --option
           Doc
    ```
    format
  - [ ] Lines are wide, but couldn't find a recommended line length

The unnecessary options are especially egregious since they take up a lot of the valueable top of the manpage.
