### ISSUE TITLE
DeprecationWarning: Flags not at the start of the expression

### ISSUE THREAD

**Issue by kbaikov** [yt-dlp/yt-dlp#1670]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Description

"DeprecationWarning: Flags not at the start of the expression" using any youtube.com url
See the log below.

*Note: even though i report it inder youtube it could potentially exist in other parts of code.

This warningcomes form [python 3.6 change](https://github.com/python/cpython/commit/db99e6ee57c5070e6ef82fd2eaa528f09f3948dc).

### Verbose log

```shell
yt-dlp.exe -Uv -F <url>
C:\Users\username\.local\pipx\venvs\yt-dlp\lib\site-packages\yt_dlp\extractor\youtube.py:4179: DeprecationWarning: Flags not at the start of the expression '(?P<pre>(?x)\n       ' (truncated)
  _url_re = re.compile(r'(?P<pre>%s)(?(channel_type)(?P<tab>/\w+))?(?P<post>.*)$' % _VALID_URL)
[debug] Command-line config: ['-Uv', '-F', '<url>']
ack
ubprocess %s is still running" % self.pid,
Resou[debug] Encodings: locale cp65001, fs utf-8, out utf-8, err utf-8, pref cp65001
[debug] yt-dlp version 2021.11.10.1
[debug] Python version 3.10.0 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg n4.4-190-g7e0d640edf-20211024 (setts), ffprobe n4.4-190-g7e0d640edf-20211024
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
yt-dlp is up to date (2021.11.10.1)
[debug] [youtube] Extracting URL: <url>
```

**Comment by pukkandan** [comment]
Check your `PYTHONWARNINGS` variable. Warnings shouldn't appear to normal end users and is harmless in our case. Unless python converts this into an error, it is not worth fixing

**Comment by kbaikov** [comment]
I configured PYTHONWARNINGS to see something like that on purpose.

The deprecation warnings are there to be fixed BEFORE it becomes and error. 
Not fixing them is a very backward and strange approach.

**Comment by elderlabs** [comment]
Silencing warnings is not the answer here. As this is a `DeprecationWarning`, it means there is a breaking change in the pipeline. If left unaddressed, `yt_dlp` will break with future versions of Python 3.

I'll look into correcting the issue myself, and report back here should I find anything. As I am a fan of [regex](https://github.com/mrabarnett/mrab-regex) over Python's default `re` library, I'm a proponent of importing it over `re` if available, otherwise falling back to `re` gracefully at import.

Tangent aside, this should be a simple fix... or not. Ignoring it, though, is not an option.

**Comment by nyuszika7h** [comment]
This is one way to fix it:
```diff
diff --git a/yt_dlp/extractor/youtube.py b/yt_dlp/extractor/youtube.py
index 632129bc6..7814df50a 100644
--- a/yt_dlp/extractor/youtube.py
+++ b/yt_dlp/extractor/youtube.py
@@ -4347,7 +4347,7 @@ class YoutubeTabIE(YoutubeBaseInfoExtractor):
 
 class YoutubePlaylistIE(InfoExtractor):
     IE_DESC = 'YouTube playlists'
-    _VALID_URL = r'''(?x)(?:
+    _VALID_URL = r'''(?x:(?:
                         (?:https?://)?
                         (?:\w+\.)?
                         (?:
@@ -4358,7 +4358,7 @@ class YoutubePlaylistIE(InfoExtractor):
                             /.*?\?.*?\blist=
                         )?
                         (?P<id>%(playlist_id)s)
-                     )''' % {
+                     ))''' % {
         'playlist_id': YoutubeBaseInfoExtractor._PLAYLIST_ID_RE,
         'invidious': '|'.join(YoutubeBaseInfoExtractor._INVIDIOUS_SITES),
     }
```

Another way:
```diff
diff --git a/yt_dlp/extractor/youtube.py b/yt_dlp/extractor/youtube.py
index 632129bc6..2e845e92a 100644
--- a/yt_dlp/extractor/youtube.py
+++ b/yt_dlp/extractor/youtube.py
@@ -4230,7 +4230,7 @@ class YoutubeTabIE(YoutubeBaseInfoExtractor):
             info_dict['entries'] = self._smuggle_data(info_dict['entries'], smuggled_data)
         return info_dict
 
-    _url_re = re.compile(r'(?P<pre>%s)(?(channel_type)(?P<tab>/\w+))?(?P<post>.*)$' % _VALID_URL)
+    _url_re = re.compile(r'(?P<pre>%s)(?(channel_type)(?P<tab>/\w+))?(?P<post>.*)$' % _VALID_URL[4:])
 
     def __real_extract(self, url, smuggled_data):
         item_id = self._match_id(url)
```

**Comment by pukkandan** [comment]
This has been fixed for youtube, but I'm pretty sure this issue exists in other extractors as well. Do let me know if you find any
