### ISSUE TITLE
[Feature Request] Reject youtube tracking

### ISSUE THREAD

**Issue by B0pol** [yt-dlp/yt-dlp#210]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running yt-dlp version **2021.03.24.1**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

With the new mandatory CONSENT cookie, you are accepting ALL tracking including YouTube history tracking and YouTube personnalized content, because off youtube-dl merged code.
<img src="https://user-images.githubusercontent.com/58657617/113325814-30601200-9319-11eb-823e-6714ecfceffe.png" width="300"> <img src="https://user-images.githubusercontent.com/58657617/113325823-3229d580-9319-11eb-9974-df2a9f93b1ae.png" width="300">
 youtube-dl maintainer sadly "don't see any problem here" so I will likely not be fixed upstream. See https://github.com/ytdl-org/youtube-dl/issues/28628
I think using PENDING+999 should be the best solution as the consent info (if not accept all = FX, but customized = F) is (most likely) stored server side, using the VISITOR_INFO1_LIVE **unique** session cookie (according to https://policies.google.com/technologies/cookies?hl=en&gl=uk#types-of-cookies). With GDPR, you shouldn't track users before consent, hence PENDING cookie should not imply consent to tracking.

**Comment by colethedj** [comment]
Interesting. When you have `PENDING+999` specifically, it only provides the popup instead of a redirect to consent.youtube.com (behaviour we have seen before). Content still loads behind, and I tested this in yt-dlp and it worked.

Out of interest, the cookie that is saved when you give consent from the popup is a little different - `YES+BG.en+V9+B+<random num>` instead of `YES+cb.20210328-17-p0.en+FX+<random num>'`

My only worry is if YouTube will keep this method alive. When they were testing the redirect to the consent page in the past weeks, I noticed that this pop up was more common than that. Maybe this was an older method they used?

**Comment by pukkandan** [comment]
@B0pol  The cookie's value does NOT affect "tracking". There are 2 main reasons.

1. Unlike the browser, we don't send any fingerprint data (assuming you dont use `--cookies`). So the `VISITOR_INFO1_LIVE` is regenerated each run

2. More importantly, the cookie does not save the "customization". It is send in the POST request to the server. You mentioned this yourself in the other thread. But `yt-dlp` (or `youtube-dl` for that matter) does not send that POST request and instead simply manually sets the cookie to an accepted value

> I think it registers server side as accepting / rejecting does not change the random? number nor other parts of the CONSENT cookie. The only difference are true/false for: set_ytc (youtube history), set_sc (search customisation), set_apw (youtube ad personalisation), set_aps (Google ad personalisation) fields in the form POST-sent to https://consent.youtube.com/s if you accept/reject the tracking

---

For the timebeing, setting the cookie to `PENDING+999` also works, but as @colethedj pointed out, this will probably be deprecated soon. And since I do not see any benefit in setting the cookie like that, it will not be implemented.
