### ISSUE TITLE
Proxy authentication example in README?

### ISSUE THREAD

**Issue by M4NH3X** [yt-dlp/yt-dlp#2419]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates

### Description

Currently in README only basic example is present IP:PORT but there is no documentation of using it when authentication is required.

```
--proxy URL
Use the specified HTTP/HTTPS/SOCKS proxy. To enable SOCKS proxy, specify a scheme. For example
socks5://127.0.0.1:1080/. Pass in an empty string (--proxy "") for direct connection
```

Discussions:
[Reddit: Any way to pass VPN username/pass to socks5 proxy using CLI?](https://www.reddit.com/r/youtubedl/comments/j5mweh/any_way_to_pass_vpn_usernamepass_to_socks5_proxy/)
[Reddit: I can't seem to work --proxy URL](https://www.reddit.com/r/youtubedl/comments/j035m5/i_cant_seem_to_work_proxy_url/)
[Linuxquestions:  Changing proxy settings for youtube-dl ](https://www.linuxquestions.org/questions/linux-newbie-8/changing-proxy-settings-for-youtube-dl-4175427857/)

Another example like this in README would be useful.
`--proxy socks5://USERNAME:PASS@SOCKSVPN_URL:PORT` => `--proxy socks5://john:hunter2@proxy.ytdlp.com:1080`
