### ISSUE TITLE
Youtube - upload_date functionality changed and requires clarified documentation

### ISSUE THREAD

**Issue by bigchipbag** [yt-dlp/yt-dlp#3081]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

using upload_date for some videos results in the date being a day ahead for some videos, I believe this is because the functionality changed in the update to use true UTC and not adjust for local time. 

Example: https://www.youtube.com/watch?v=ey8B30KyOMQ
Date published (on youtube) is reported as November 8th, 2021 because it adjusts to my local time
yt-dlp is reporting it as November 9th, 2021 as seen in logs as it was 4am UTC

This has changed compared to previous versions, as I run batch scripts and noticed way more web traffic than normal on directories which have videos already in it. 

The following image has the latest download details on the left, and the previous versions' download on the right. 
https://i.imgur.com/JWBbu1F.png

Note that the timestamp is the same but the title is adjusted. It's not clear that the functionality of "upload_date" has changed/now defaults to naming it based on UTC. 

Ideally this could be changed in the documentation to specify that it names based on UTC, since the documentation doesn't specify either way 

### Verbose log

```shell
PS I:\Video\YT-Archive> .\yt-dlp.exe -vU
[debug] Command-line config: ['-vU']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.03.08 [535eb16] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: none
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08
Current Build Hash 728c6e072133451bbe26825b329577e4a40242af74582a73d6d8a10ac45c6b3e
Updating to version 2022.03.08.1 ...
Updated yt-dlp to version 2022.03.08.1
PS I:\Video\YT-Archive> .\yt-dlp.exe -S 'height:720' -o "%(uploader)s/%(title)s-%(upload_date)s.%(ext)s" -w -c --throttled-rate 100K https://www.youtube.com/watch?v=ey8B30KyOMQ
[youtube] ey8B30KyOMQ: Downloading webpage
[youtube] ey8B30KyOMQ: Downloading android player API JSON
[info] ey8B30KyOMQ: Downloading 1 format(s): 22
[download] DaThings\{YTP} ~ Pocket Mans!-20211109.mp4 has already been downloaded
[download] 100% of 33.36MiB
PS I:\Video\YT-Archive>
```

**Comment by bigchipbag** [comment]
> **Hoping for a quick return to the UTC date.** I have to return to an older version of ytdlp

This will not happen as he mentioned, but if you revert to version 2022.02.04 it retains the old date. Use until broken, then exclude anything published before the last successful run. 

For example, if you run the script June 5th, then June 10th, and it is broken on June 10th, exclude using --dateafter <DATE - in the format it expects>

This is my plan.

**Comment by nastia-diaphan** [comment]
I will not revert to 2022.02.04 if it is not planed to revert to the previous time. I will write a piece of code to rename the video file on the fly, according to the now date.

but it is strange: US time does not exist [https://www.time.gov/](url)

**Comment by pukkandan** [comment]
No need to be pedantic. Since we only get the date and not the time, it is difficult to pinpoint the exact time zone that is being used. But from checking various videos, we know that it's approx 6hrs behind UTC. Hence why I called it "US time"

**Comment by pukkandan** [comment]
> at my side this news is a little disaster.

> -o "%(upload_date)s.%(id)s.%(format_id)s.%(ext)s"

because of this? Why use `upload_date` as a unique identifier? What happens if the upload date extraction breaks? You should only use `id` and `extractor_key` as a primary keys. Sometimes even they can change, but we try to prevent changes to these unless there is no other way (since this breaks `--download-archive`)

In any case, using non-UTC time for `upload_date` was definitely a bug. The code in many places assume it is UTC time, and that is what most extractors return (I would like to say all, but it's difficult to confirm if the same bug exists elsewhere)

> > Hoping for a quick return to the UTC date. I have to return to an older version of ytdlp

> This will not happen as he mentioned,

That is not what I said. Instead, yt-dlp currently returns the UTC date. It is older versions that don't

**Comment by bigchipbag** [comment]
I also realized this could be corrected for my batches using --download-archive (somehow I missed that switch)

**Comment by pukkandan** [comment]
Do not depend on filenames to detect duplicates for the long term. Filenames can change for a variety of reasons. (1) Video metadata including title changes all the time. (2) The file extension changes if the preferred format changes. (3) Extraction of some metadata fields may break. (4) Less likely, but the default outtmpl may change

Also, it is much slower than using archive

**Comment by nastia-diaphan** [comment]
I have made some test that confirm that new date is based on UTC time.
The old one is based on a Local, possibly a US one, but certainly not on the uploader's one.

Here is 2 samples
**1** `aA_vNhr3mhU` posted in Russia, **21** March 23:45 UTC 
_Uploader's Local:_ "videoPrimaryInfoRenderer":{"title":{"runs":[{"text":"**22** марта 2022 г."}]
_NEW:_ videoPrimaryInfoRenderer: "dateText":{"simpleText":"Mar **21**, 2022"}
_OLD:_ playerMicroformatRenderer: "publishDate":"2022-03-**21**","ownerChannelName":"KING PUBG","uploadDate":"2022-03-**21**"}}
**2** `pe-XoZyfacE` posted in Russia, **22** March 00:15 UTC 
_Uploader's Local:_ "videoPrimaryInfoRenderer":{"title":{"runs":[{"text":"**22** марта 2022 г."}]}
_NEW:_ "videoPrimaryInfoRenderer": "dateText":{"simpleText":"Mar **22**, 2022"}}
_OLD:_ playerMicroformatRenderer: "publishDate":"2022-03-**21**","ownerChannelName":"Вика рулит👑","uploadDate":"2022-03-**21**"}}

I agree. the new date must be kept.

Now I have to delete some duplicated files, and rename some others. It's time to reconsider the naming pattern. I added date at the beginning of files for easy sorting.

Keep on the good job....

**Comment by coletdjnz** [comment]
For YouTube it is not perfect right now. For scheduled/current/past live streams/premieres, we still _prefer_ the old "US" timezone date (see below). But everything else should be in UTC.

https://github.com/yt-dlp/yt-dlp/blob/d5820461e85a9d3d0b2a019f988d4469bfbcc3ee/yt_dlp/extractor/youtube.py#L3644-L3646
https://github.com/yt-dlp/yt-dlp/pull/2223#issuecomment-1008485139

(just adding this here for documentation sake)
