### ISSUE TITLE
Add support for Facebook (Meta) Workplace videos

### ISSUE THREAD

**Issue by DaBomby** [yt-dlp/yt-dlp#3107]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

United States

### Example URLs

- Single Video: https://abc.workplace.com/100028380075587/videos/336048507351199/ 

### Description

Please add support for Facebook (Meta) Workplace videos. This would be similar to the support that currently exists for private Facebook videos.

### Verbose log

```shell
youtube-dl.exe -f "bestvideo+bestaudio" --write-thumbnail --write-description --console-title --merge-output-format "mp4" --all-subs --embed-thumbnail --add-metadata --add-header "Cookie: datr______" https://abc.workplace.com/100028380075587/videos/336048507351199/ -v [debug] System config: [] [debug] User config: [] [debug] Custom config: [] [debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252 [debug] youtube-dl version 2021.01.16 [debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041 [debug] exe versions: ffmpeg N-100592-g42ee3898c8, ffprobe N-100592-g42ee3898c8 [debug] Proxy map: {} [generic] 336048507351149: Requesting header WARNING: Falling back on generic information extractor. [generic] 336048507351149: Downloading webpage [generic] 336048507351149: Extracting information ERROR: Unsupported URL: https://abc.workplace.com/100028380075587/videos/336048507351199/ Traceback (most recent call last): File "C:\youtube-dl\ytdl-org\tmpfnvjp7pc\build\youtube_dl\YoutubeDL.py", line 805, in wrapper File "C:\youtube-dl\ytdl-org\tmpfnvjp7pc\build\youtube_dl\YoutubeDL.py", line 826, in __extract_info File "C:\youtube-dl\ytdl-org\tmpfnvjp7pc\build\youtube_dl\extractor\common.py", line 532, in extract File "C:\youtube-dl\ytdl-org\tmpfnvjp7pc\build\youtube_dl\extractor\generic.py", line 3467, in _real_extract youtube_dl.utils.UnsupportedError: Unsupported URL: https://abc.workplace.com/100028380075587/videos/336048507351199/
```

**Comment by doe1080** [comment]
[Workplace from Meta](https://www.workplace.com/) will cease operations on May 31, 2026
