### ISSUE TITLE
Meta-info for YouTube premieres and live events

### ISSUE THREAD

**Issue by leegee** [yt-dlp/yt-dlp#3419]
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Scenario: using the program to gather meta information about a YouTube video, rather than to download the video itself(`-j --skip-download`)

As an end user,
when the video ID is that for a "live event" that has not yet started
or when the video ID is that for a "premiere" that has yet to broadcast,

then I would like to receive all available meta information as JSON, rather than a notice on `STDERR`.

### Verbose log

```shell
[debug] Command-line config: ['-vU', '-j', '--skip-download', 'HJILB-Sryko']
[debug] Encodings: locale cp65001, fs utf-8, out utf-8 (No ANSI), err utf-8 (No ANSI), pref cp65001
[debug] yt-dlp version 2022.04.08 [7884ade] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2021-09-05-git-a947098558-full_build-www.gyan.dev (setts), ffprobe 2021-09-05-git-a947098558-full_build-www.gyan.dev
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [youtube] Extracting URL: HJILB-Sryko
[youtube] HJILB-Sryko: Downloading webpage
[youtube] HJILB-Sryko: Downloading android player API JSON
ERROR: [youtube] HJILB-Sryko: Premieres in 6 days
  File "yt_dlp\extractor\common.py", line 641, in extract
  File "yt_dlp\extractor\youtube.py", line 3377, in _real_extract
  File "yt_dlp\extractor\common.py", line 1161, in raise_no_formats
```

**Comment by pukkandan** [comment]
Add `--ignore-no-formats-error`
