### ISSUE TITLE
Verbose mode should tell you downloader invoked.

### ISSUE THREAD

**Issue by EvanCarroll** [yt-dlp/yt-dlp#3703]
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Youtube-dl's verbose mode should tell you what downloader is being used to fetch the file.

### Verbose log

When you run something like 

```shell
yt-dlp "https://www.youtube.com/watch?v=NPBnphbYGFw" -v
```

I would like if rather than, 

```text
[debug] Invoking downloader on "https://rr1---sn-q4flrnle.googlevideo.com/videoplayback?expire=1652243655&ei=Z-h6YoX_EOnQlu8P282V6AI&ip=2603%3A300c%3A184d%3A1400%3A%3A4e0e&id=o-ALTncWiJhGCYpl4CiKyCOuKRRn2zpaN7ibt4i74YTg5X&itag=271&source=youtube&requiressl=yes&mh=MA&mm=31%2C26&mn=sn-q4flrnle%2Csn-5uaezn7e&ms=au%2Conr&mv=m&mvi=1&pl=38&initcwndbps=2057500&vprv=1&mime=video%2Fwebm&gir=yes&clen=305755282&dur=8073.332&lmt=1645227445100969&mt=1652221735&fvip=1&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAJs48aKe-GUU95hrtrrgSS855uoCG0hwNyadHViTu1uZAiBC56VQ6tlDLAdy6H4-kmLHGU1kbBiLcoJHUE2LVSYqZQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAKwETaT2ioVuN9UHfW-YrqJ_Jh8SMWe5HEWhTuP0KSx3AiAdhDMiOWZsHh6_QqFx4y6amBBA_kTcf4vwz-wl4W-cxg%3D%3D"
```

It said, **WHAT** downloader was invoked. This would help people new to the project to work on the downloaders.

Like this, 

> [debug] Invoking downloader [common.py] on

**Comment by EvanCarroll** [comment]
This will help trouble shoot the problem mentioned here. Thanks.

**Comment by EvanCarroll** [comment]
@pukkandan this still doesn't tell me why one is slower then the other. But it does tell me they both use the http downloader. Do you have any ideas of how this can be improved?

Run these two commands.

```
./yt-dlp.sh -v "https://www.youtube.com/watch?v=NPBnphbYGFw" -qiJ | jq -r '.formats[] | select(.format_id == "251").url' | xargs ./yt-dlp.sh -v -o out.webm
```

```
./yt-dlp.sh -v "https://www.youtube.com/watch?v=NPBnphbYGFw" 
```

My guess from the above linked issue is that only one of them sets the download options `http_chunk_size`? Perhaps the downloader that receives the option, or the thing that sets the option should dump the options somewhere?

Ideally, I'm building up to a question of why doesn't targetting the url `googlevideo.com` set the download chunk size? If we know it's needed indirectly when you hit the viewer page, then shouldn't it be needed on direct download too?

**Comment by pukkandan** [comment]
> My guess from the above linked issue is that only one of them sets the download options http_chunk_size? Perhaps the downloader that receives the option, or the thing that sets the option should dump the options somewhere?

See `downloader_options` and `http_headers` in the json. If you try to download the URL without these, ofc it will be slow!

PS: I don't get what is the point of your command anyway. If you can explain that (**open another issue**), perhaps I can help more

**Comment by EvanCarroll** [comment]
I think the point of that command is more of a question for @[theofficialgman](https://github.com/theofficialgman), I'll invite him to open the issue. Just to be clear, I get that those options **need** to be provided. I do not understand why they're implicit (provided in downloader_options or http_headers) in one command and not the other.

**Comment by pukkandan** [comment]
>  I do not understand why they're implicit (provided in downloader_options or http_headers) in one command and not the other.

https://github.com/ytdl-org/youtube-dl/issues/30568#issuecomment-1123192366

**Comment by theofficialgman** [comment]
having a verbose mode that spit out all required information to facilitate fast downloads would be nice, yes.
so if that means setting http_chunk_size, setting the user agent, etc, it should all be output in the verbose output.

**Comment by EvanCarroll** [comment]
It still doesn't make sense to me to have that chunk information set in the thing that downloads the index page rather than the thing that downloads the video, which is what I understand is the architectural reason for this bheavior.

```text
fn crawl_page(url) {
  fn download_video( url, options );
}
```

Seems less ideal than

```text
fn get_default_options( url ) {
  // get global defaults override URL defaults
}

fn download_video( url ) {
  options = get_default_options(url);
}

fn crawl_page(url) {
  fn download_video( url, override_options );
}
```
