### ISSUE TITLE
Generated manpage shows long options with single hyphen, not double hyphen

### ISSUE THREAD

**Issue by mhmdanas** [yt-dlp/yt-dlp#3814]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Since 0f06bcd (found using `git bisect`), the man page generated by `make yt-dlp.1` shows long options with a single hyphen instead of the correct double hyphen, e.g. `-help` instead of `--help`. The correctly generated manpage has this line for the `--help` option:
```groff
-h, --help
```
The manpage with single hyphens has this line instead:
```groff
.B \-h, \[en]help
```

Additionally, some, but not all, of long option mentions in prose are also affected.

Reproducible on both 2022.05.18 and current `master`.

### Verbose log

The problem is not in the yt-dlp program itself.

**Comment by pukkandan** [comment]
The bug is in #3684
