### ISSUE TITLE
After building with pyinstaller ytdlp just refuses to work

### ISSUE THREAD

**Issue by someziggyman** [yt-dlp/yt-dlp#3835]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Steps to reproduce (using MacOS on my end and PyInstaller 5.1)
1) git clone https://github.com/yt-dlp/yt-dlp.git
2) /usr/local/bin/python3 ./pyinst.py --target-architecture universal2 --onedir 

Same thing if I build with --onefile param in the end. 
 
Then try using the resulting yt-dlp_macos in dist folder. Logs for both cases below.
Is this specific to me or just some typo/bug in __init__.py or elsewhere? Or even ytdlp_plugins related, looking at the last line... any help is appreciated. 

-----
**Updated:
@pukkandan  This issue has been introduced lately, cause building with source code from https://github.com/yt-dlp/yt-dlp/releases/tag/2022.05.18 works just fine. So it's something after May 18**

### Verbose log

```shell
/Downloads/yt-dlp/dist/yt-dlp_macos/yt-dlp_macos -v -F "https://www.youtube.com/watch?v=TbulIdDCgFE"
Traceback (most recent call last):
  File "yt_dlp/__main__.py", line 13, in <module>
    import yt_dlp
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "yt_dlp/__init__.py", line 14, in <module>
    from .downloader import FileDownloader
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "yt_dlp/downloader/__init__.py", line 27, in <module>
    from .external import FFmpegFD, get_external_downloader
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "yt_dlp/downloader/external.py", line 11, in <module>
    from ..postprocessor.ffmpeg import EXT_TO_OUT_FORMATS, FFmpegPostProcessor
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "yt_dlp/postprocessor/__init__.py", line 38, in <module>
    _PLUGIN_CLASSES = load_plugins('postprocessor', 'PP', globals())
  File "yt_dlp/utils.py", line 4919, in load_plugins
    plugins_spec.loader.exec_module(plugins)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
NotADirectoryError: [Errno 20] Not a directory: '/Downloads/yt-dlp/dist/yt-dlp_macos/yt-dlp_macos/ytdlp_plugins/postprocessor/__init__.py'
[6349] Failed to execute script '__main__' due to unhandled exception!

------
LOG 2 
/usr/local/bin/python3 ./pyinst.py --target-architecture universal2 --onefile
------
/Downloads/yt-dlp/dist/yt-dlp_macos -v -F "https://www.youtube.com/watch?v=TbulIdDCgFE" 
Traceback (most recent call last):
  File "yt_dlp/__main__.py", line 13, in <module>
    import yt_dlp
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "yt_dlp/__init__.py", line 14, in <module>
    from .downloader import FileDownloader
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "yt_dlp/downloader/__init__.py", line 27, in <module>
    from .external import FFmpegFD, get_external_downloader
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "yt_dlp/downloader/external.py", line 11, in <module>
    from ..postprocessor.ffmpeg import EXT_TO_OUT_FORMATS, FFmpegPostProcessor
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "yt_dlp/postprocessor/__init__.py", line 38, in <module>
    _PLUGIN_CLASSES = load_plugins('postprocessor', 'PP', globals())
  File "yt_dlp/utils.py", line 4919, in load_plugins
    plugins_spec.loader.exec_module(plugins)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
NotADirectoryError: [Errno 20] Not a directory: '/Downloads/yt-dlp/dist/yt-dlp_macos/ytdlp_plugins/postprocessor/__init__.py'
[6476] Failed to execute script '__main__' due to unhandled exception!
```
