### ISSUE TITLE
[CentOS 7.9] can't run yt-dlp_linux

### ISSUE THREAD

**Issue by jazz1611** [yt-dlp/yt-dlp#4417]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

hello,

i download yt-dlp from "https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_linux" to server in CentOS 7.9 x64 and failed to run. i still can run normal version "yt-dlp 	Platform-independent zipimport binary. Needs Python (recommended for Linux/BSD)"

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[root@centos-16gb-fsn1-3 ~]# ./yt-dlp -Uv
[debug] Command-line config: ['-Uv']
DeprecationWarning: Support for Python version 3.6 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/3764  for more details.
                    You will no longer receive updates on this version! Please update to Python 3.7 or above
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out UTF-8, error UTF-8, screen UTF-8
[debug] yt-dlp version 2022.07.18 [135f05e] (zip)
[debug] Python 3.6.8 (CPython 64bit) - Linux-3.10.0-1160.42.2.el7.x86_64-x86_64-with-centos-7.9.2009-Core (glibc 2.3.4)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: avconv -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)

[root@centos-16gb-fsn1-3 ~]# ./yt-dlp_linux
[32643] Error loading Python lib '/tmp/_MEI20JUOj/libpython3.10.so.1.0': dlopen: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/_MEI20JUOj/libpython3.10.so.1.0)
```

**Comment by pukkandan** [comment]
See pinned issue

**Comment by pukkandan** [comment]
Actually, PRs to "fix" this is welcome. See https://github.com/yt-dlp/yt-dlp/issues/3764#issuecomment-1166499925. So I'll keep the issue open

**Comment by jazz1611** [comment]
@pukkandan so, the CentOS 7 can only run the `yt-dlp` in version python 3.6, right?

**Comment by pukkandan** [comment]
> ModuleNotFoundError: No module named '_ssl'

The python seems to be built without the ssl module which yt-dlp needs

**Comment by gamer191** [comment]
@jazz1611 https://stackoverflow.com/questions/5128845/importerror-no-module-named-ssl might be helpful, although I haven't tested any of it's solutions

**Comment by pukkandan** [comment]
OP should be fixed by https://github.com/yt-dlp/yt-dlp/pull/5423
