### ISSUE TITLE
[minor feature] compile option to deactivate autoupdate

### ISSUE THREAD

**Issue by ghost** [yt-dlp/yt-dlp#4471]
### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

autoupdate should be deactivated when yt-dlp is distributed with package managers and app stores. The likes of, linux distros, pip,, chocolety, brew etc... Currently, packagers either just leave it in, or they faf around with patches that periodically break.

A compile option should deactivate the option, and also remove it from the manual. 

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Feel free to make a PR for this

**Comment by pukkandan** [comment]
Related https://github.com/yt-dlp/yt-dlp/issues/4134

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/issues/4134#issuecomment-1162532840 is the currently recommended solution. While I think it is a sufficient solution, I can understand concerns of merge-conflicts for such a patch.

Are you a package maintainer? While I could implement something like this, I don't know what kind of implementation someone packaging actually needs - and rather than guessing, would like to hear from people who actually build the ports (cc @yurivict)

My initial idea is to implement a `VARIANT` variable in version.py which can be used to override yt-dlp's internal variant detection. So for example, someone can set `VARIANT = 'apt'` and the auto-updater will say:
```
[debug] Command-line config: ['--ignore-config', '-vU']
[debug] Encodings: locale cp65001, fs utf-8, pref cp65001, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.01.01 [f640e42ff] (apt*)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Python 3.10.5 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-106550-g072101bd52-20220410 (fdk,setts), ffprobe N-106624-g391ce570c8-20220415, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.1
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.01.01
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2022.07.18/_update_spec
ERROR: It looks like you installed yt-dlp with a package manager or setup.py; Use that to update
```

Is this sufficient? I can provide the ability to change this variant as part of `devscripts/update-version.py`. Or, you can always manually change it in version.py by any means you see fit

With an appropriate PR, we could also improve the Makefile to set the variant from the environment

PS: Once an implementation is finalized, I would be very reluctant to change it even if better ideas pop up

**Comment by Lesmiscore** [comment]
Does it block `rclone selfupdate` somehow, assuming rclone was installed with any package manager? If not, I don't see the point

**Comment by yurivict** [comment]
I added the recommended patch and it is fine IMO.

When a new version is found it recommends to use the package manager to update it.

**Comment by pukkandan** [comment]
> i'm not a maintainer, i just noticed that packagers are chasing their tails with autoupdaters

Read https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-anyone-going-to-need-the-feature. If this was an actual issue for package maintainers, I expect **them** to request this. The only person who has ever asked for something like this (yurivict) is satisfied by the current solution. There is no point in working on features that nobody will use!

I too use scoop and apt for packages and both of them handle yt-dlp's self-update gracefully. In case of scoop, the version number scoop shows will go out of sync when using `-U`, but this is not a big deal. 

> (this is especially bad with chocolatey).

As I remember, chocolatey just uses our pre-built binaries. In that case, there is absolutely nothing I can do to for this issue. Any solution I can provide require that the maintainer be willing to build the executables themselves - which I doubt will happen for choco. If any maintainer has shown interest in doing this, pls give me link to any relevant conversation (or, you can invite them to discuss under this issue)

> you should talk to packagers of several systems. What they are doing can vary.

I am not going to go around and DM package maintainers. If there are people you know are facing this issue that you claim exist, feel free to point them here so that we can discuss the matter

**Comment by yurivict** [comment]
IMO you should add a build-time option that would do the same that [this](https://cgit.freebsd.org/ports/tree/www/yt-dlp/files/patch-yt__dlp_update.py) patch from the FreeBSD port does.

**Comment by pukkandan** [comment]
That is basically what I proposed in https://github.com/yt-dlp/yt-dlp/issues/4471#issuecomment-1198266075

**Comment by yurivict** [comment]
> That package how ever is on the responsibility of the user to update it.

On FreeBSD packages aren't a responsibility of users. They are rebuilt centrally, and the user only needs to run ```pkg upgrade``` to upgrade all of them every once in a while.

**Comment by pukkandan** [comment]
Wdym "removal"? You want -U to do nothing, or to completely remove that option? For former, read my above comment again. The latter will not be done

**Comment by pukkandan** [comment]
Re-read https://github.com/yt-dlp/yt-dlp/issues/4471#issuecomment-1198266075

**Comment by pukkandan** [comment]
NO! Why don't read what I actually wrote in the above comments? I am not going to implement this just because you think it may be helpful when you don't plan to use the feature yourself. https://github.com/yt-dlp/yt-dlp/issues/4471#issuecomment-1198443486

If you actually value this issue, instead of asking me to "just do that", try and bring people who'd actually benefit from this into the conversation. I didn't immediately close the issue because I thought this could be used to start a discussion on the matter. But if it is turning into a useless back and forth, I will close and lock it

**Comment by Unit193** [comment]
I'm a little late to the party and only happened upon this bug report by chance, but I'm the Debian maintainer of yt-dlp.  Until [recently](https://git.unit193.net/cgit/users/unit193/yt-dlp.git/commit/?id=474433dde3f50fe9b6e787d815576064e98957b2) the patch included in Debian also removed the update feature and updated the help text, now it simply does the latter.  I'd looked into the feature and noticed the update check bails if it detects yt-dlp was installed by a package manager, so dropped the removal of that but left in where the patch disables the help text so we don't advertise the feature since it doesn't actually update.

If you were  to include the VARIANT style of thing as mentioned above, it'd be neat if the help text could be updated to reflect that.  Informing the user of backport channels could be neat as well, but this doesn't sound like the job of upstream to me. :)

**Comment by pukkandan** [comment]
> If you were to include the VARIANT style of thing as mentioned above, it'd be neat if the help text could be updated to reflect that.

`-U` still checks if the user is in the latest yt-dlp version. So instead of removing the helptext, I could modify it to reflect that. Something like: 

    -U, --update    Report the latest version of this program

**Comment by Unit193** [comment]
Yep!  Sounds great to me.  Noting it'll update if in standalone mode or not installed via a package manager would be fine too.  Thanks for considering it, would love to drop that patch entirely.

**Comment by pukkandan** [comment]
Done. Example usage: https://github.com/yt-dlp/yt-dlp/blob/70b2340909d8d917f71d20181614fd7392d3f7f0/.github/workflows/build.yml#L92

The variant name will appear in `--verbose` head and the message (`-M`) will appear in both the helptext of `-U` and in the error message. Like this:

```
❯ yt-dlp -vU
[debug] Command-line config: ['--ignore-config', '-vU']
[debug] Encodings: locale cp65001, fs utf-8, pref cp65001, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05ef6] (pip)
...
ERROR: You installed yt-dlp with pip or using the wheel from PyPi; Use that to update
```

    -U, --update                                        Check if updates are available. You installed yt-dlp with pip or using the wheel from PyPi; Use that to update

Setting a custom message is optional. As long as a variant is set, the update will be blocked and a generic error message is shown

**Comment by Unit193** [comment]
Thanks!  Updated, using that option too.
