### ISSUE TITLE
[Compile] How to solve: No module named 'devscripts.utils'

### ISSUE THREAD

**Issue by nicolaasjan** [yt-dlp/yt-dlp#4603]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.08.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Linux Mint 20.3; Python 3.8.10

Today, after the new `2022.08.08` release, I tried to compile myself again and it failed at `make`:

```
make
/usr/bin/env python3 devscripts/make_lazy_extractors.py yt_dlp/extractor/lazy_extractors.py
Traceback (most recent call last):
  File "devscripts/make_lazy_extractors.py", line 12, in <module>
    from devscripts.utils import get_filename_args, read_file, write_file
ModuleNotFoundError: No module named 'devscripts.utils'
make: *** [Makefile:134: yt_dlp/extractor/lazy_extractors.py] Fout 1
```
What am I missing here?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by marillat** [comment]
I see also the same under Debian unstable python 3.10.5

**Comment by pukkandan** [comment]
Could you verify whether this fixes the issue?
```diff
diff --git a/setup.py b/setup.py
index aebe1dead..3a3961ed4 100644
--- a/setup.py
+++ b/setup.py
@@ -1,5 +1,9 @@
 #!/usr/bin/env python3

+import os
+import sys
+sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
+
 import os.path
 import subprocess
 import sys
```

**Comment by pukkandan** [comment]
I cannot reproduce. For attempting to debug, can you check a few things?
1. Does the file `devscripts/utils.py` exist?
2. Does the error occor when running `make lazy-extractors`?
3. What about when directly running `python3 devscripts/make_lazy_extractors.py`?

**Comment by nicolaasjan** [comment]
> Does the file devscripts/utils.py exist?

Yes.

> Does the error occor when running make lazy-extractors?

Yes.

```
make lazy-extractors
/usr/bin/env python3 devscripts/make_lazy_extractors.py yt_dlp/extractor/lazy_extractors.py
Traceback (most recent call last):
  File "devscripts/make_lazy_extractors.py", line 12, in <module>
    from devscripts.utils import get_filename_args, read_file, write_file
ModuleNotFoundError: No module named 'devscripts.utils'
make: *** [Makefile:134: yt_dlp/extractor/lazy_extractors.py] Fout 1
```

> What about when directly running python3 devscripts/make_lazy_extractors.py?

```
python3 devscripts/make_lazy_extractors.py
Traceback (most recent call last):
  File "devscripts/make_lazy_extractors.py", line 12, in <module>
    from devscripts.utils import get_filename_args, read_file, write_file
ModuleNotFoundError: No module named 'devscripts.utils'

```

**Comment by pukkandan** [comment]
Add this and show me what you get when running `python3 devscripts/make_lazy_extractors.py`

```diff
diff --git a/devscripts/make_lazy_extractors.py b/devscripts/make_lazy_extractors.py
index 01bd88ae6..5aeca705c 100644
--- a/devscripts/make_lazy_extractors.py
+++ b/devscripts/make_lazy_extractors.py
@@ -5,6 +5,9 @@
 import sys

 sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
+print(sys.path[0])
+import os.path
+assert os.path.exists(os.path.join(sys.path[0], 'devscripts/utils.py'))


 from inspect import getsource
```

**Comment by frkli1965** [comment]
Having the exact same issues under Ubuntu 22.04 (Linux 5.19) with Python 3.10.4...

Everything was working fine up until Saturday btw, if that helps...

Kind regards

**Comment by pukkandan** [comment]
I know which commit caused the issue (115add43876964956917bf596c1d0b148c5b3c26), but I don't know why it is happening. If I can't figure it out in a few days, I'll revert it

**Comment by nicolaasjan** [comment]
FWIW,
Making `lazy_extractors.py` on Windows 10 with `Python 3.10.6` went fine.
And building succeeded.

**Comment by bashonly** [comment]
for any/all impacted by this issue, what happens if you try changing
`from devscripts.utils import`...
to
`from utils import`...

in the following files:
`make_issue_template.py`
`make_lazy_extractors.py`
`make_readme.py`
`make_supportedsites.py`
`prepare_manpage.py`
`set-variant.py`
`update-formulae.py`
`update-version.py`

(if you're on gnu/linux you can run this from the yt-dlp directory:)
`sed -i 's/from\sdevscripts\.utils\simport/from utils import/g' devscripts/*.py`

**Comment by nicolaasjan** [comment]
@bashonly
Then it works. 🙂
Don't know if this is the right approach though.

**Comment by marillat** [comment]
@bashonly
setup.py is still broken
```I: pybuild base:239: python3.10 setup.py clean 
Traceback (most recent call last):
  File "/home/marillat/src/yt-dlp-2022.08.08/setup.py", line 15, in <module>
    from utils import read_file, read_version
ModuleNotFoundError: No module named 'utils'```

**Comment by pukkandan** [comment]
But everything else got fixed?

**Comment by pukkandan** [comment]
> Then it works. 🙂
> Don't know if this is the right approach though.

If that works, it is an acceptable solution (Though I still have no clue what caused the issue). Thanks @bashonly 

> setup.py is still broken

This should not be done in `setup.py`. It was not previously broken, correct?

**Comment by marillat** [comment]
Of course `setup.py` is broken.
`setup.py` is called from the Makefile
```$ python3 setup.py sdist 
Traceback (most recent call last):
  File "/home/marillat/src/yt-dlp-2022.08.08/setup.py", line 15, in <module>
    from devscripts.utils import read_file, read_version
ModuleNotFoundError: No module named 'devscripts.utils'```

**Comment by trialuser02** [comment]
It conflicts with debian devscripts package. Try to rename /usr/lib/python3/dist-packages/devscripts directore or remove devscripts package. But I think this conflict should be fixed by upstream.

**Comment by marillat** [comment]
> It conflicts with debian devscripts package. Try to rename /usr/lib/python3/dist-packages/devscripts directore or remove devscripts package. But I think this conflict should be fixed by upstream.

Yes renaming the directory fix the build with pybuild and yes this issue should be fixed here.

**Comment by pukkandan** [comment]
lol, I didn't even imagine there could be a third-party library called devscripts! thanks @trialuser02! Ofc, I can't reproduce since I don't have that package installed... Now that we know the problem, I'll push a fix asap

**Comment by nicolaasjan** [comment]
Thanks!
Everything is as it should be now. 🙂
