### ISSUE TITLE
CONTRIBUTING.md out of date

### ISSUE THREAD

**Issue by mbway** [yt-dlp/yt-dlp#487]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] ~I've verified that I'm running yt-dlp version **2021.07.07**~
- [ ] ~I've checked that all provided URLs are alive and playable in a browser~
- [ ] ~I've checked that all URLs and arguments with special characters are properly quoted or escaped~
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Description

I want to contribute a feature to yt-dlp so the first thing I did was read CONTRIBUTING.md. I found that it is identical to the youtube_dl CONTRIBUTING.md document (except for one character difference in an example URL). The instructions for running are obviously not correct and from the setup.py it looks like yt-dlp has dropped support for python 2 so other instructions in that document are incorrect.
There are probably other differences in code organisation and code style which differ from youtube_dl so it would be nice to customize this document so that it isn't misleading.

**Comment by pukkandan** [comment]
You are right, I haven't touched CONTRIBUTING.md yet. To be fair, almost all the guidelines are the same as upstream (except for the py2 deprecation). But I will look into modifying to better reflect the state of yt-dlp. 

PRs are also very welcome in this regard. In general, I am bad at writing documentation and it takes me way too long to document even the simplest things 😫 

> except for one character difference in an example URL

ha, that was caused due to me find-replacing all instances of that typo, lol
