### ISSUE TITLE
[Makefile] Refactor to be easier to maintain

### ISSUE THREAD

**Issue by pukkandan** [yt-dlp/yt-dlp#5131]
<details>
<summary>Template</summary>

### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

</details>

### Provide a description that is worded well enough to be understood

There are a few issues with the current makefile that makes it difficult to maintain

- [ ] 1. `make clean` has to be kept in sync with `.gitignore` (same for `make pypi-files` and `MANIFEST.in`)
- [x] 2. `CODE_FOLDERS` is hardcoded and needs frequent modifications 6f638d325e1878df304822c6bf4e231e06dae89a 059bc4db1975698dca53278a0fcc23d428b7658a 4a61501db9369c813f913dc491c36951f8b087ad
- [x] 3. The allowed levels of nesting of the code folders is also hardcoded separately [`a057779#diff`](https://github.com/yt-dlp/yt-dlp/commit/a057779d5e706f7bb8721a6c46cca47f0925f682#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52) 6f638d325e1878df304822c6bf4e231e06dae89a

(1) is likely the hardest to fix, but also the smallest problem. I'd be happy as long as (2) & (3) are fixed

Ideally, any solution should only use the UNIX-compliant core utilities, but exceptions can be made, especially for GNU coreutils

**Comment by dirkf** [comment]
Trivial point: it could be helpful to parametrise the program name
```make
WHATEVER = yt_dlp
...
all: lazy-extractors $(WHATEVER) doc pypi-files
...
# etc
```

**Comment by dirkf** [comment]
For item#1, you could define variables containing lists of cleanable/ignorable patterns to use in the `clean...` targets of the `Makefile` and a `.gitignore` target whose recipe is a shell script to which the lists are passed. The script could, eg, know to add the `!test/testdata/**` line.

For item#2, you could hide a flag file `.here_be_code` (eg) in each desired directory and generate `CODE_FOLDERS` with a _find_ command.

Using `CODE_FOLDERS` isn't it already possible to avoid item#3, the variable depth wildcard matches? Eg:
```diff
-	touch -t 200001010101 zip/yt_dlp/*.py zip/yt_dlp/*/*.py
+	touch -t 200001010101 $(for cf in $CODE_FOLDERS; do printf 'zip/%s/*.py' "$cf")
```

**Comment by bashonly** [comment]
something like this would address issues 2 and 3. (tested)
```diff
diff --git a/Makefile b/Makefile
index 8f335927d..122f9f5df 100644
--- a/Makefile
+++ b/Makefile
@@ -73,17 +73,27 @@ test:
 offlinetest: codetest
 	$(PYTHON) -m pytest -k "not download"
 
-# XXX: This is hard to maintain
-CODE_FOLDERS = yt_dlp yt_dlp/downloader yt_dlp/extractor yt_dlp/postprocessor yt_dlp/compat
+SOURCE_ROOT = yt_dlp
+CODE_FOLDERS = $(shell \
+        cd $(SOURCE_ROOT) && \
+        folders=$$(find . \( -type d -name '*' \) -print | sed -r 's/^\./$(SOURCE_ROOT)/') ;\
+        for f in $$folders ; do \
+          printf '%s' $$f | grep -Eq '(__pycache__|pytest_cache)' && continue ;\
+          printf '%s ' $$f ;\
+        done)
 yt-dlp: yt_dlp/*.py yt_dlp/*/*.py
 	mkdir -p zip
 	for d in $(CODE_FOLDERS) ; do \
 	  mkdir -p zip/$$d ;\
 	  cp -pPR $$d/*.py zip/$$d/ ;\
 	done
-	touch -t 200001010101 zip/yt_dlp/*.py zip/yt_dlp/*/*.py
 	mv zip/yt_dlp/__main__.py zip/
-	cd zip ; zip -q ../yt-dlp yt_dlp/*.py yt_dlp/*/*.py __main__.py
+	zip_files=__main__.py ;\
+	cd zip && for d in $(CODE_FOLDERS) ; do \
+	  [ "$$(printf '%s' $$d/*.py)" != "$$d/*.py" ] && zip_files="$$(printf '%s ' $$d/*.py)$$zip_files" ;\
+	done ;\
+	touch -t 200001010101 $$zip_files ;\
+	zip -q ../yt-dlp $$zip_files
 	rm -rf zip
 	echo '#!$(PYTHON)' > yt-dlp
 	cat yt-dlp.zip >> yt-dlp
```

**Comment by bashonly** [comment]
2 and 3 are solved by 868d2f60a7cb59b410c8cbfb452cbdb072687b81

1 may be unsolvable: You *could* parse `.gitignore` with some shell/python scripting called from the Makefile, but really doing anything other than hardcoding the args for an `rm -rf` line would be extremely unsafe. I personally wouldn't use a `make clean` recipe where I can't see what it's doing just by a cursory examination of the Makefile

**Comment by Grub4K** [comment]
Closed in 868d2f60a7cb59b410c8cbfb452cbdb072687b81
