### ISSUE TITLE
yt-dlp_min.exe v2022.10.04 has no file version information?

### ISSUE THREAD

**Issue by awei78** [yt-dlp/yt-dlp#5135]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

As the title says, file version information is empty, such as product version.
They existed in previous versions and yt-dlp.exe and and yt-dlp_x86.exe.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
`py2exe` seems to have changed their API. We'll need to migrate to their new API and figure out how to add version info back. For the time-being, I'll pin the py2exe we use to an older version

**Comment by gamer191** [comment]
For anyone who's interested in working on this https://github.com/py2exe/py2exe/blob/master/docs/migration.md and [py2exe's changelog](https://github.com/py2exe/py2exe/releases) may be useful

**Comment by awei78** [comment]
see, thanks!
