### ISSUE TITLE
Break up README file into manageable chunks

### ISSUE THREAD

**Issue by tripleo1** [yt-dlp/yt-dlp#5246]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Breakup README.rd file

It's too dern long

I'll do it myself and push a PR if you like...

Also, provide a pdf for those who can't let go, or need a single reference (ie for printing as a cheat sheet)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
wc -l  < README.md
```

**Comment by pukkandan** [comment]
The readme will be kept as a single file. I hate docs where I can't search everything in one place. Ideas for better organizing the sections are welcome. 

> Also, provide a pdf for those who can't let go, or need a single reference (ie for printing as a cheat sheet)

We used to have an autogenerated readthedocs, but it was dropped since nobody was willing to maintain it (when changes to readme breaks the auto-generation). If you are are willing to maintain it long term, a PR for that is welcome as well. Otherwise, you can always just convert the markdown to pdf with third party tools

**Comment by tripleo1** [comment]
Noted
