### ISSUE TITLE
Add armv7 & aarch64 builds

### ISSUE THREAD

**Issue by MrOctopus** [yt-dlp/yt-dlp#5436]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

It would be nice if additional builds of yt-dlp could be added for armv7 & aarch64 to new releases of the software.  I have already done this for a private repository, but could also create a pull-reques to add the feature to the official yt-dlp github build workflow if it is desired. 

Use-case:
Using binary builds of yt-dlp on arm based platforms such as raspberry pis

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
> but could also create a pull-reques to add the feature to the official yt-dlp github build workflow if it is desired.

Pls do so. Make sure to also update readme and update.py
