### ISSUE TITLE
[twitter] Add file meta-data to twitter broadcasts like modified date

### ISSUE THREAD

**Issue by AdamSaketume26** [yt-dlp/yt-dlp#5942]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2023.01.02** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Example URLs

https://twitter.com/i/broadcasts/1kvJpmZQgNLxE
https://api.twitter.com/1.1/broadcasts/show.json?include_events=true&ids=1kvJpmZQgNLxE&broadcastVersionMap=

### Provide a description that is worded well enough to be understood

I am trying to save past broadcasts on Twitter, but I noticed it doesn't automatically change the date to match the broadcast's date.  I tried using different arguments but it still didn't work. The data required is available on the endpoint https://api.twitter.com/1.1/broadcasts/show.json?include_events=true&ids=

So with the example url already given it would be https://api.twitter.com/1.1/broadcasts/show.json?include_events=true&ids=1kvJpmZQgNLxE&broadcastVersionMap=

and the property needed is created_at_ms

also if a broadcast is deleted (404 when you visit) then the broadcast id's object is empty. So for example again with the output from above, it would just be {
"broadcasts": {
"1kvJpmZQgNLxE": {}
},
"events": {}
}

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-N48', '--embed-metadata', '--mtime', 'https://twitter.com/i/broadcasts/1kvJpmZQgNLxE']
[debug] User config: []
[debug] System config: []
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.02 [d83b0ad] (win32_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 5.1.2-essentials_build-www.gyan.dev (setts), ffprobe 5.1.2-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1754 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.02, Current version: 2023.01.02
yt-dlp is up to date (2023.01.02)
[twitter:broadcast] Extracting URL: https://twitter.com/i/broadcasts/1kvJpmZQgNLxE
[twitter:broadcast] 1kvJpmZQgNLxE: Downloading guest token
[twitter:broadcast] 1kvJpmZQgNLxE: Downloading JSON metadata
[twitter:broadcast] 28_1608032331650007041: Downloading JSON metadata
[twitter:broadcast] 1kvJpmZQgNLxE: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1kvJpmZQgNLxE: Downloading 1 format(s): replay-5500
[debug] Invoking hlsnative downloader on "https://prod-fastly-us-west-2.video.pscp.tv/Transcoding/v1/hls/Qe1YFJTEijMb-1WS1XeaCPplLm0913crOd4Tm3HymSNwriuv3Ml-tqGgxQcOvuvzpO095YBU6BU-yEtZuef7eA/transcode/us-west-2/periscope-replay-direct-prod-us-west-2-public/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInZlcnNpb24iOiIyIn0.eyJFbmNvZGVyU2V0dGluZyI6ImVuY29kZXJfc2V0dGluZ18xMDgwcDMwXzEwIiwiSGVpZ2h0IjoxMDgwLCJLYnBzIjo1NTAwLCJXaWR0aCI6MTkyMH0.OImMZabKYJ0cs9CnIapU-4aBk6KNBiJxi1hh-6l4BZ4/playlist_16774523345717652049.m3u8?type=replay"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 482
[download] Destination: SpaceX - Starlink Mission [1kvJpmZQgNLxE].mp4
[debug] File locking is not supported. Proceeding without locking
WARNING: The download speed shown is only of one thread. This is a known issue and patches are welcome
[download] 100% of  180.68MiB in 00:00:03 at 59.15MiB/s
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json "file:SpaceX - Starlink Mission [1kvJpmZQgNLxE].mp4"
[FixupM3u8] Fixing MPEG-TS in MP4 container of "SpaceX - Starlink Mission [1kvJpmZQgNLxE].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:SpaceX - Starlink Mission [1kvJpmZQgNLxE].mp4" -map 0 -dn -ignore_unknown -c copy -f mp4 "-bsf:a" aac_adtstoasc -movflags "+faststart" "file:SpaceX - Starlink Mission [1kvJpmZQgNLxE].temp.mp4"
[Metadata] Adding metadata to "SpaceX - Starlink Mission [1kvJpmZQgNLxE].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:SpaceX - Starlink Mission [1kvJpmZQgNLxE].mp4" -map 0 -dn -ignore_unknown -c copy -write_id3v1 1 -metadata "title=SpaceX - Starlink Mission" -metadata "purl=https://twitter.com/i/broadcasts/1kvJpmZQgNLxE" -metadata "comment=https://twitter.com/i/broadcasts/1kvJpmZQgNLxE" -metadata "artist=SpaceX" -movflags "+faststart" "file:SpaceX - Starlink Mission [1kvJpmZQgNLxE].temp.mp4"
```

**Comment by pukkandan** [comment]
`--mtime` uses the modified time of the file on server - not uploaded/broadcasted date

**Comment by AdamSaketume26** [comment]
im confused because when i download all the file times of created modified accessed get set to the time the download completes

**Comment by AdamSaketume26** [comment]
I thought of that after I made my comment and tried it without parallel download -N and it still didnt work

**Comment by bashonly** [comment]
Hm yeah the modified times on the server do not correspond to the broadcast date. You can see these with `yt-dlp --print-traffic` or by passing the URLs to `curl --head` 

from the API data:
```json
"created_at_ms": "1672219758273",
```
```
$ date -d@1672219758.273 -u
Wed Dec 28 09:29:18 AM UTC 2022
```

from the server:
```
$ curl --head "https://prod-fastly-us-west-2.video.pscp.tv/Transcoding/v1/hls/Qe1YFJTEijMb-1WS1XeaCPplLm0913crOd4Tm3HymSNwriuv3Ml-tqGgxQcOvuvzpO095YBU6BU-yEtZuef7eA/transcode/us-west-2/periscope-replay-direct-prod-us-west-2-public/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInZlcnNpb24iOiIyIn0.eyJFbmNvZGVyU2V0dGluZyI6ImVuY29kZXJfc2V0dGluZ18xMDgwcDMwXzEwIiwiSGVpZ2h0IjoxMDgwLCJLYnBzIjo1NTAwLCJXaWR0aCI6MTkyMH0.OImMZabKYJ0cs9CnIapU-4aBk6KNBiJxi1hh-6l4BZ4/playlist_16774523345717652049.m3u8?type=replay"
HTTP/2 200 
content-type: application/x-mpegURL
last-modified: Wed, 04 Jan 2023 09:52:14 GMT
```

```
$ curl --head "https://prod-fastly-us-west-2.video.pscp.tv/Transcoding/v1/hls/Qe1YFJTEijMb-1WS1XeaCPplLm0913crOd4Tm3HymSNwriuv3Ml-tqGgxQcOvuvzpO095YBU6BU-yEtZuef7eA/transcode/us-west-2/periscope-replay-direct-prod-us-west-2-public/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInZlcnNpb24iOiIyIn0.eyJFbmNvZGVyU2V0dGluZyI6ImVuY29kZXJfc2V0dGluZ18xMDgwcDMwXzEwIiwiSGVpZ2h0IjoxMDgwLCJLYnBzIjo1NTAwLCJXaWR0aCI6MTkyMH0.OImMZabKYJ0cs9CnIapU-4aBk6KNBiJxi1hh-6l4BZ4/chunk_1672220723861580294_484_a.ts"
HTTP/2 200 
content-type: video/mp2t
last-modified: Wed, 04 Jan 2023 07:08:29 GMT
```

It's worth noting that the twitter extractor also doesn't extract the timestamp values for broadcasts, but fixing that unfortunately wouldn't have any effect on `--mtime`

**Comment by AdamSaketume26** [comment]
> Hm yeah the modified times on the server do not correspond to the broadcast date. You can see these with yt-dlp --print-traffic or by passing the URLs to curl --head

> It's worth noting that the twitter extractor also doesn't extract the timestamp values for broadcasts, but fixing that unfortunately wouldn't have any effect on --mtime

is there something i am missing? if we add support to extract the proper timestamps from the api why cant we pass it into the method that declares --mtime?

**Comment by pukkandan** [comment]
> if we add support to extract the proper timestamps from the api why cant we pass it into the method that declares --mtime? or modify --mtime to see if the url matches a twitter broadcast and if so extract the timestamp from the api

We can, but not currently implemented https://github.com/yt-dlp/yt-dlp/issues/903

**Comment by AdamSaketume26** [comment]
2 years ago, wish i could help but idk how
