### ISSUE TITLE
Sub Meta.io Website Request

### ISSUE THREAD

**Issue by 151SoGood** [yt-dlp/yt-dlp#6017]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Australia; US

### Example URLs

- Single video: https://submeta.io/@lachlangiles/courses/introduction/97811573-e516-4cbf-83d6-d37eb62754d0
- Playlist: https://submeta.io/@lachlangiles/courses/introduction

### Provide a description that is worded well enough to be understood

Currently yt-dlp does not support this website, requesting any workaround and/or if support can be added. Happy to provide any further details where required. Thank you very much

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\foo>yt-dlp https://submeta.io/@lachlangiles/courses/no-gi-open-guard-overview/2c201783-a7f7-41b8-8e66-acb04ba52869 -vU
[debug] Command-line config: ['https://submeta.io/@lachlangiles/courses/no-gi-open-guard-overview/2c201783-a7f7-41b8-8e66-acb04ba52869', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2023.01.06
[debug] Python version 3.9.7 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg 2021-10-03-git-2761a7403b-full_build-www.gyan.dev, ffprobe 2021-10-03-git-2761a7403b-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
ERROR: It looks like you installed yt-dlp with a package manager, pip, setup.py or a tarball. Use that to update
[debug] [generic] Extracting URL: https://submeta.io/@lachlangiles/courses/no-gi-open-guard-overview/2c201783-a7f7-41b8-8e66-acb04ba52869
[generic] 2c201783-a7f7-41b8-8e66-acb04ba52869: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] 2c201783-a7f7-41b8-8e66-acb04ba52869: Downloading webpage
[generic] 2c201783-a7f7-41b8-8e66-acb04ba52869: Extracting information
ERROR: [generic] Unsupported URL: https://submeta.io/@lachlangiles/courses/no-gi-open-guard-overview/2c201783-a7f7-41b8-8e66-acb04ba52869
Traceback (most recent call last):
  File "C:\Users\foo\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\extractor\common.py", line 585, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\foo\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\extractor\generic.py", line 3712, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://submeta.io/@lachlangiles/courses/no-gi-open-guard-overview/2c201783-a7f7-41b8-8e66-acb04ba52869
Traceback (most recent call last):
  File "C:\Users\foo\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\extractor\common.py", line 585, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\foo\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\extractor\generic.py", line 3712, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://submeta.io/@lachlangiles/courses/no-gi-open-guard-overview/2c201783-a7f7-41b8-8e66-acb04ba52869

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\foo\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1227, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\foo\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1252, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\foo\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\extractor\common.py", line 601, in extract
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [generic] Unsupported URL: https://submeta.io/@lachlangiles/courses/no-gi-open-guard-overview/2c201783-a7f7-41b8-8e66-acb04ba52869
```

**Comment by bashonly** [comment]
Note for devs: Looks like the site uses Vimeo embeds that aren't detected by Vimeo extractor. There's a whole lot of Next JS data in the webpages. All content is behind authwall but there are free courses/videos available

@151SoGood the workaround for now is a bit of a process. You can use your browser's dev tools to find requests to `vimeo.com/api`, and look in the `html` field of the JSON response. You can copy the `https://player.vimeo.com` URL that you find in there and pass that to yt-dlp, adding this to your command: `--referer "https://submeta.io/"`

**Comment by 151SoGood** [comment]
Excellent thank you.
