### ISSUE TITLE
vrv.co has been absorbed by Crunchyroll

### ISSUE THREAD

**Issue by ualaa1** [yt-dlp/yt-dlp#6322]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

https://vrv.co/watch/GRG5N58PR/Samurai-7:The-Pupil
Gives a 404 error when attempting to download

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://vrv.co/watch/GRG5N58PR/Samurai-7:The-Pupil']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.02.17 [a0a7c01] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2023-02-19-git-2aec86695a-full_build-www.gyan.dev (setts), ffprobe 2023-02-19-git-2aec86695a-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1782 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.02.17, Current version: 2023.02.17
yt-dlp is up to date (2023.02.17)
[vrv] None: Downloading webpage
[vrv] Extracting URL: https://vrv.co/watch/GRG5N58PR/Samurai-7:The-Pupil
[vrv] GRG5N58PR: Downloading resource path JSON metadata
[vrv] GRG5N58PR: Downloading CMS Signing JSON metadata
[vrv] GRG5N58PR: Downloading object JSON metadata
ERROR: [vrv] GRG5N58PR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 693, in extract
  File "yt_dlp\extractor\vrv.py", line 159, in _real_extract
  File "yt_dlp\extractor\vrv.py", line 72, in _call_cms
  File "yt_dlp\extractor\common.py", line 1047, in download_content
  File "yt_dlp\extractor\common.py", line 1011, in download_handle
  File "yt_dlp\extractor\common.py", line 881, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 838, in _request_webpage

  File "yt_dlp\extractor\common.py", line 820, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3726, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by hendursaga** [comment]
Isn't this site now known as Crunchyroll?

**Comment by bashonly** [comment]
> Isn't this site now known as Crunchyroll?

Looks like it, I get redirected to the CR frontpage from every VRV link.

The extractor should be removed, but if anyone can find any VRV links with video IDs that work when plugged into a crunchy watch URL format, then we should improve the CR extractor's `_VALID_URL` to match the `vrv.co` domain. All the video IDs from the VRV links I've found have 404'd when plugged into a crunchy URL, though
