### ISSUE TITLE
Fork build workflow fails

### ISSUE THREAD

**Issue by nicolaasjan** [yt-dlp/yt-dlp#6415]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.03** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

After having forked the project; synced @ commit 4a6272c  and running the release workflow, I get this at "Publish release":
 
```
HTTP 422: Validation Failed (https://api.github.com/repos/nicolaasjan/yt-dlp/releases)
body is too long (maximum is 125000 characters)
Error: Process completed with exit code 1.
```

Related (?):
[[Bug]: changelog is too long](https://github.com/goreleaser/goreleaser/issues/2647)

Is there anything I can do to prevent GitHub from complaining?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
N/A
```

**Comment by Grub4K** [comment]
The code to search for the last tag goes back and uses all commits when not found. The related code is found in `CommitRange._find_last_tag`. That also fails when you dont push a version commit bc it cannot find the tag in linear history. I had no idea how to fix that but I thought forks copied the Tags from upstream and so limited themselves that way? If not, that should maybe be hard limited and also noted in "Forking" on the wiki? Additionally we can make it so at most 100 items are taken and the total outout is under x characters?

**Comment by pukkandan** [comment]
We can simply stop when a `Release xxx` commit is encountered?

**Comment by pukkandan** [comment]
```diff
diff --git a/devscripts/make_changelog.py b/devscripts/make_changelog.py
index 07aa3285b..13393c2da 100644
--- a/devscripts/make_changelog.py
+++ b/devscripts/make_changelog.py
@@ -312,7 +312,7 @@ def _get_commits_and_fixes(self, default_author):
             commit = Commit(commit_hash, short, authors)
             if skip:
                 logger.debug(f'Skipped commit: {commit}')
-                continue
+                break

             fix_match = self.FIXES_RE.search(commit.short)
             if fix_match:
```
should work

**Comment by nicolaasjan** [comment]
https://github.com/nicolaasjan/yt-dlp/releases/tag/2023.03.04.100510
Temporary workaround successful. 🙂
