### ISSUE TITLE
meta:tags language mapping for audio and video?

### ISSUE THREAD

**Issue by Askadelion** [yt-dlp/yt-dlp#6453]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

How to assign the language mata:tag according to the audio track and video track.

What commands do I need to assign the correct language to the meta:tag of the audio and video files.
for Crunchyroll, but also other sites.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Pls elaborate with examples and verbose logs

**Comment by Askadelion** [comment]
yt-dlp output after DL for Video & Audio not Lang:META:TAG in MKV only for Subtitle
![grafik](https://user-images.githubusercontent.com/41443013/223206494-74aedd2a-643b-4d74-902e-fea157f3cf47.png)

this is how it should look
![grafik](https://user-images.githubusercontent.com/41443013/223207529-0dbb473a-7a72-4eca-b652-de2300b082bf.png)

hope that is enough for you as an example
you won't be able to do anything with my log because I want to know which commands I need so that it will be there after the download.

**Comment by pukkandan** [comment]
`--embed-metadata` should add language tags to audio. If that doesn't work, verbose logs are needed for further investigation

**Comment by Susexe** [comment]
@pukkandan, is there a reason `--embed-metadata` is required for this? Ideally, I’d like to include only audio language tags (as subtitles do by default), without embedding any additional metadata.

**Comment by bashonly** [comment]
> is there a reason `--embed-metadata` is required for this?

@Susexe because adding metadata requires ffmpeg to write the full media file to disk again, thus it should only be done with the user's consent (i.e. if they've passed `--embed-metadata`).

---

> Ideally, I’d like to include only audio language tags (as subtitles do by default), without embedding any additional metadata.

You could clear all of the other metadata using `--parse-metadata`:
```
--parse-metadata ":(?P<meta_>)"
```
and then manually set the language tag again, e.g.:
```
--parse-metadata "video:%(requested_formats.1.language)s:%(meta1_language)s"
```
(this is assuming you are downloading and merging 1 video and 1 audio format)

Putting it all together, your yt-dlp command would look like this:
```
yt-dlp --embed-metadata --parse-metadata ":(?P<meta_>)" --parse-metadata "video:%(requested_formats.1.language)s:%(meta1_language)s" "URL"
```

---

Alternatively, you could hack the embedding into the ffmpeg arguments during merging, but then you would need to hardcode the language code in your arg:
```
--ppa "Merger+ffmpeg:-metadata:s:1 language=eng"
```
The full yt-dlp command would look like this:
```
yt-dlp --ppa "Merger+ffmpeg:-metadata:s:1 language=eng" "URL"
```

**Comment by Susexe** [comment]
@bashonly, thank you! Both solutions worked flawlessly. The first one preserved the chapters, which I actually needed anyway. I realized that `--ppa -map_chapters -1` can be used to remove them when necessary.

I ended up with a hybrid solution, using `--ppa` to achieve the following:

1. Remove the video `title` tag (`ISO Media file produced by Google Inc.`).
2. Manually set the video track language, since it’s usually undefined.
3. Control the default audio track, as all audio streams are marked as default by design.

Please let me know if there’s a more elegant way to accomplish these tasks without relying on `--ppa`.

```bat
yt-dlp ^
  -f "bv*+ba[language=en]+ba[language=fr]" ^
  --audio-multistreams ^
  --embed-metadata ^
  --parse-metadata ":(?P<meta_>)" ^
  --parse-metadata "video:%(requested_formats.1.language)s:%(meta1_language)s" ^
  --parse-metadata "video:%(requested_formats.2.language)s:%(meta2_language)s" ^
  --ppa "Merger+ffmpeg:-map_metadata -1 -metadata:s:v:0 language=eng -disposition:a:0 default -disposition:a:1 0" ^
  "URL"
```
