### ISSUE TITLE
[YouTube] Bogus invalid start time warnings

### ISSUE THREAD

**Issue by jidanni** [yt-dlp/yt-dlp#6811]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

We observe
```
WARNING: [youtube] Invalid start time (887.0 < 0) for chapter "20200616"
````
triggered by
```
"description" : "20200616 14:47",
```
Indeed
```
$ expr 60 \* 14 + 47
887
```
Here the innocent YouTuber has noted the date and time he took a video,
and yt-dlp assumes he meant something else.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--update', '--verbose', '--dump-json', '--skip-download', 'https://www.youtube.com/shorts/ar2amyIdpnU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (debian*)
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-6.1.0-7-amd64-x86_64-with-glibc2.36 (OpenSSL 3.0.8 7 Feb 2023, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.3-1 (setts), ffprobe 5.1.3-1
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[youtube] Extracting URL: https://www.youtube.com/shorts/ar2amyIdpnU
[youtube] ar2amyIdpnU: Downloading webpage
[youtube] ar2amyIdpnU: Downloading android player API JSON
WARNING: [youtube] Invalid start time (887.0 < 0) for chapter "20200616"
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] ar2amyIdpnU: Downloading 1 format(s): 135+251
```

**Comment by pukkandan** [comment]
We are trying to parse it as chapters. Our options are:
1. Do not parse chapters from description
2. Parse and ignore errors
3. Parse and warn for errors

Of these, 3 is the best option imo. Do you disagree?

**Comment by jidanni** [comment]
Then do please add something similar to
```
       --ignore-no-formats-error
              Ignore "No video formats" error.  Useful for extracting metadata
              even  if the videos are not actually available for download (ex‐
              perimental)
```

**Comment by dirkf** [comment]
There's a distinction between the routines that get chapter lists from structured data and `_extract_chapters_from_description()`.

In the former case valid data is expected and it's reasonable to warn if it doesn't make sense; in the latter case it seems strange to warn that something not intended to be a chapter list wasn't one.

The `strict` parameter of `_extract_chapters_helper()` could be extended* (or a further parameter added) to indicate that the supposed chapter list might not be reliably identified. In that case the warning could be skipped if no item in the list is valid; in particular, if there is just a single invalid item, as here.

\* either by changing the semantics of `False`, or by allowing it to have a dict value with keys like `order`, `expected`, where the existing `True` value is equivalent to `{'order': True, 'expected': True}`, the existing `False` value is equivalent to `{'order': False, 'expected': True}`, and the proposed behaviour would be `{'order': False, 'expected': False}`.

**Comment by jidanni** [comment]
In fact, I am saddened to find that cycles are being wasted examining data that I never intended it to examine.

I mean I'm feeding it a site that I know doesn't go by some strange customs  that the app is expecting. So I should be able to tell it that, no it is not on what it thinks it is, so don't waste any computations looking for something that won't be there.

I mean, I am not interested in silencing error messages. I am interested in turning off the thing looking for stuff that won't be there in the first place.
And all this should be able to be controlled by the user from the command line without even needing any source code.

**Comment by pukkandan** [comment]
If each CPU cycle i important to you, yt-dlp is the wrong tool to use. Ths parsing will not be disabled.
