### ISSUE TITLE
repo: git log broken by SSH signature

### ISSUE THREAD

**Issue by baltakatei** [yt-dlp/yt-dlp#7322]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

As of 2023-06-15, the SSH signature of commit [edbe5b5](https://github.com/yt-dlp/yt-dlp/commit/edbe5b589dd0860a67b4e03f58db3cd2539d91c2) dated 2023-05-25 breaks `git log` operations for git v2.30.2 and GnuPG 2.2.27, the latest versions of these packages in Debian 11 Bullseye. Commit information is printed until commit edbe5b5 is reached, upon which `gpg` throws an error and `git` exits prematurely.

I found the offending commit by running `$ nskip=84; nc=1; clear; if git log --skip="$nskip" -n "$nc"; then echo true; else echo false;` with different integer values for `nskip` and `nc` and seeing which commands returned `false`.

The solution is probably to inform **yt-dlp** users who are browsing its version control history to upgrade `git` to at least v2.34.0 as recommended in the [GitLab documentation about signing with SSH keys](https://docs.gitlab.com/ee/user/project/repository/ssh_signed_commits/#verify-commits-locally). (upgrading to derivatives of the new Debian stable: Debian 12 Bookworm gives you git v2.39.2 and GnuPG 2.2.40) This issue threw me for a loop since this is my first time encountering an SSH signature in the wild. A workaround for someone who can't easily upgrade `git` may be to run `git log` operations with the option `-n` and `--skip` options with values that will exclude commit `edbe5b5`. In other words, if you only need to check the past dozen commits, just run `git log -n 12`.

If this post is inappropriate for the forum, please feel free to delete it.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
baltakatei@debian11:~/git/yt-dlp$ "$(which git)" --version; "$(which gpg)" --version; GIT_TRACE=1 git log edbe5b5
git version 2.30.2
gpg (GnuPG) 2.2.27
libgcrypt 1.8.8
Copyright (C) 2021 Free Software Foundation, Inc.
License GNU GPL-3.0-or-later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /home/baltakatei/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
08:19:27.837866 git.c:444               trace: built-in: git log edbe5b5
08:19:27.839652 run-command.c:664       trace: run_command: unset GIT_PAGER_IN_USE; LESS=FRX LV=-c pager
Aborted
BUG: gpg-interface.c:283: bad signature '-----BEGIN SSH SIGNATURE-----
U1NIU0lHAAAAAQAAADMAAAALc3NoLWVkMjU1MTkAAAAg09D33Nl94GUNGEYxjWTRAV6UeP
NrsHj9hDufPfxbBtMAAAADZ2l0AAAAAAAAAAZzaGE1MTIAAABTAAAAC3NzaC1lZDI1NTE5
AAAAQF0t2EfXgnCnOXPpTzcqiG/8k+kHwtgb+IMEd37u0OhfQrR+qbUf7YAAvL8Uhg59jM
f7pPXnZDNNSeeQ3CBI9w0=
-----END SSH SIGNATURE-----
```

**Comment by pukkandan** [comment]
This is way too off-topic to be added to our Readme. But you are welcome to PR it to https://github.com/yt-dlp/yt-dlp/wiki
