### ISSUE TITLE
ERROR: [twitter] 98764321: Unrecognized subtask ID "DenyLoginSubtask"

### ISSUE THREAD

**Issue by Shohreh** [yt-dlp/yt-dlp#7579]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hello,

It worked until today, but I'm now getting this error when trying to download a video from Twitter:

```
c:\youtube-dlp.exe --username joe --password blah --abort-on-error --twofactor 123456 -o test.mp4 https://twitter.com/blah/status/98764321
ERROR: [twitter] 98764321: Unrecognized subtask ID "DenyLoginSubtask"
```

Downloading still works OK when using a web[-based app](https://twittervideodownloader.com/), so it looks specific to YDLP. Am I the only one having this issue?

Thank you.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8 (No VT), error utf-8 (No VT), screen utf-8 (No VT)
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (win_x86_exe)
[debug] Python 3.7.9 (CPython x86 32bit) - Windows-7-6.1.7601-SP1 (OpenSSL 1.1.1g  21 Apr 2020)
[debug] exe versions: ffmpeg N-109165-g9f5a9a7499-20221122 (setts), ffprobe N-109165-g9f5a9a7499-20221122
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: 7ce646283f2c437e2dc28e3008c892702824b6174f381d82b8e68c5bdb6be3b2
yt-dlp is up to date (stable@2023.07.06)
```

**Comment by bashonly** [comment]
> I'm now getting this error when trying to download a video from Twitter

Can you please show a full verbose log of the yt-dlp login failing?
This looks like something that was missed in the extractor's login implementation

> Downloading still works OK when using a web-based app, so it looks specific to YDLP. Am I the only one having this issue?

You no longer need to be logged in with yt-dlp in order to download twitter videos. Or if you are downloading age-restricted content, you can pass cookies instead of `-u`/`-p`

**Comment by Shohreh** [comment]
Thanks for the info. It's working again. Looks like a site-bug indeed.

**Comment by gamer191** [comment]
Potentially relevant (but also MIT licensed, so I doubt it can be used):
https://github.com/kenchan0130/unofficial-twitter-api-client-go/blob/main/twitter/session.go#L65

**Comment by bashonly** [comment]
Apparently `DenyLoginSubtask` is sent from twitter upon a "suspicious login" attempt, but I'm not sure what exactly raises twitter's suspicion.

Closing this again since I can't repro it and I don't have enough info to patch it properly

If anyone else experiences this error, please run your command again with `-v --write-pages` and post the verbose log here. The dumped pages should not be posted publicly, but could be sent privately to the dev working to solve this
