### ISSUE TITLE
ERROR: [twitter] Unrecognized subtask ID "ArkoseLogin"

### ISSUE THREAD

**Issue by obscenelyvague** [yt-dlp/yt-dlp#7625]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Worldwide

### Provide a description that is worded well enough to be understood

Worked initially after support was added for login. Some recent Twitter change must've broken it. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Encodings: locale utf-8, fs utf-8, pref utf-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip)
[debug] Python 3.11.4 (CPython aarch64 64bit) - Linux-4.19.229-disrupt-gb9e45bb24f0e-aarch64-with-libc (OpenSSL 3.1.1 30 May 2023, libc)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[twitter] Downloading login page
[twitter] Downloading flow token
[twitter] Submitting JS instrumentation response
[twitter] Submitting username
ERROR: [twitter] 1680995202201206785: Unrecognized subtask ID "ArkoseLogin"; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 707, in extract
    self.initialize()
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 613, in initialize
    self._perform_login(username, password)
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/yt_dlp/extractor/twitter.py", line 278, in _perform_login
    raise ExtractorError(f'Unrecognized subtask ID "{next_subtask}"')
```

**Comment by bashonly** [comment]
I can't reproduce with my account, but `ArkoseLogin` appears to be a captcha challenge. We can add a better error message for that but otherwise nothing we can do. Pass cookies instead if you get this when trying to login

**Comment by obscenelyvague** [comment]
Issue no longer persists after acquiring a new IP. Carrier provides dynamic IPs and perhaps some sort of check was triggered due to unwanted traffic.
