### ISSUE TITLE
[extractor/hypeddit] Add extractor

### ISSUE THREAD

**Issue by pelim** [yt-dlp/yt-dlp#7948]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

[Example Chrome Hypeddit-Extension](https://github.com/phimhp7/Hypeddit-Extension) (only aws endpoint with raw audio file

metadata extraction needs to implemented

### example endpoints

[https://hypeddit.com/ct3t1y](https://hypeddit.com/ct3t1y
)
[https://hypeddit-gates-prod.s3.amazonaws.com/ct3t1y_main](https://hypeddit-gates-prod.s3.amazonaws.com/ct3t1y_main
)

### tasks

- [ ] update feature request
- [ ] implement extension

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pelim** [comment]
will take core over this feature and submit PR

**Comment by bashonly** [comment]
Is this a site support request? Add a verbose log of an attempt to download from the site

**Comment by neopostmodern** [comment]
Is this really not planned or just missing info?
Here's the verbose output for above URL (`yt-dlp -v "https://hypeddit.com/ct3t1y"`):
```
[debug] Command-line config: ['-v', 'https://hypeddit.com/ct3t1y']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.05.27 from yt-dlp/yt-dlp [12b248ce6] (pip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.6.10-76060610-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.46.0, pyxattr-0.7.2, requests-2.31.0, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-2.0.4, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1820 extractors
[generic] Extracting URL: https://hypeddit.com/ct3t1y
[generic] ct3t1y: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] ct3t1y: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://hypeddit.com/ct3t1y
Traceback (most recent call last):
  File "/home/neopostmodern/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1606, in wrapper
    return func(self, *args, **kwargs)
  File "/home/neopostmodern/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1741, in __extract_info
    ie_result = ie.extract(url)
  File "/home/neopostmodern/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 734, in extract
    ie_result = self._real_extract(url)
  File "/home/neopostmodern/.local/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 2514, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://hypeddit.com/ct3t1y
```
