### ISSUE TITLE
Wrong version in source code archives

### ISSUE THREAD

**Issue by Ywo0x** [yt-dlp/yt-dlp#823]
## Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [ ] I've verified that I'm running yt-dlp version **2021.08.10**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] The provided URLs do not contain any DRM to the best of my knowledge
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
$ wget -nv https://github.com/yt-dlp/yt-dlp/archive/refs/tags/2021.08.10.tar.gz
2021-08-29 19:31:10 URL:https://codeload.github.com/yt-dlp/yt-dlp/tar.gz/refs/tags/2021.08.10 [1707625/1707625] -> "2021.08.10.tar.gz" [1]
$ tar x -zf 2021.08.10.tar.gz
$ ls
2021.08.10.tar.gz  yt-dlp-2021.08.10
$ cat yt-dlp-2021.08.10/yt_dlp/version.py
from __future__ import unicode_literals

__version__ = '2021.08.02'
```

## Description

The source code archives from releases page contains the wrong versions:

yt-dlp-2021.08.10 = 2021.08.02
yt-dlp-2021.08.02 = 2021.07.24
yt-dlp-2021.07.24 = 2021.07.21

etc.

**Comment by pukkandan** [comment]
The archive contains the state of the source code right before release. So the version is going to be one behind

**Comment by Ywo0x** [comment]
Sorry if I'm misunderstanding. Why not just create the tag as last thing for the release? e.g. after updating version.py etc? Then the created archives on releases page will be correct.

As package maintainers uses the source archives generated by GitHub, the version number is wrong in most distros that packages yt-dlp.

**Comment by Ashish0804** [comment]
it makes sense to be of new version since that's the date of archiving.
v2021.08.02 is the current version and hasn't been archived so doesn't make sense for it to be in the archives

**Comment by pukkandan** [comment]
> Why not just create the tag as last thing for the release? e.g. after updating version.py etc? 

This is an artifact of how the build is automated. I'll see how this can be done

> As package maintainers uses the source archives generated by GitHub

I recommend that package maintainers use the tarball we release alongside the binaries. However, I did find a bug in that tarball that would prevent you from doing so, but it has now been fixed

**Comment by pukkandan** [comment]
#880 will add a zip with `--onedir` version. Here's a test release: https://github.com/pukkandan/yt-dlp-dev/releases/tag/2021.09.19.2

**Comment by pukkandan** [comment]
@Ywo0x For today's release, the archives should have the correct version

**Comment by Ywo0x** [comment]
@pukkandan I can confirm that the problem is solved. Thanks.
