### ISSUE TITLE
render html page with video and comments

### ISSUE THREAD

**Issue by milahu** [yt-dlp/yt-dlp#9424]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

it would be nice to have an option to additionally produce an html file
with the data from the `info.json` file and subtitles

motivation:
youtube is horrible for browsing comments (lazy loading, infinite scroll, no search, no filter)
so when an interesting video has thousands of comments
then i use `yt-dlp` to download the comments to an `info.json` file
and render the comments to html, so i have all comments on one page

limitation:
chromium does not load subtitles from the `file` protocol
so im using `data` urls to embed subtitles into the html file

proof of concept

<details>
<summary>
html_from_info_json.py
</summary>

```py
#! /usr/bin/env python3

# TODO render subtitles text with click-to-seek
# similar to https://docdrop.org/video/1pXmuh1AUQQ/

# FIXME picture-in-picture mode sucks
# because there are no subtitles
# so we should use CSS to keep the video in a fixed position

# TODO more fine-grained seek-by-key (left arrow, right arrow)

# TODO make subtitles editable

# TODO allow to enable scroll-with-video for subtitles

# TODO show comments-with-timestamps next to subtitles (at the same time position) (similar to youtube live chat)

# TODO render uploader/channel name, description (collapsed by default), upload date, view count, votes

# TODO allow to collapse comment threads from all Y positions (not only from the top Y position)

import json
import urllib.parse
import os
import sys
import urllib.request
import base64
import datetime
import re
import glob

info_json_path = sys.argv[1]

base_path = ".".join(info_json_path.split(".")[0:-2])

base_name = os.path.basename(base_path)

video_path = None
video_type = None
try:
  video_path = next(filter(lambda x: re.search(r"\.(mp4|webm|mkv|ogv|avi)$", x, re.I), glob.glob(base_path + ".*")))
  video_type = video_path.split(".")[-1]
except StopIteration:
  pass

page_title = os.path.basename(video_path) if video_path else base_name

fd = open(p)
info = json.load(fd)
fd.close()

#for key in ["id", "title", "fulltitle", "comment_count", "like_count", "channel", "channel_follower_count", "upload_date", "duration_string"]:
#  print(key, info[key])

#print("comment 0", info["comments"][0])

comment_tree = {}

for comment in info["comments"]:
  if comment["parent"] == "root":
    comment_tree[comment["id"]] = comment
  else:
    parent = comment_tree[comment["parent"]]
    if not "children" in parent:
      parent["children"] = {}
    parent["children"][comment["id"]] = comment

print(f'<!doctype html>')
print(f'<html lang="en">')
print(f'  <head>')
print(f'    <meta charset="utf-8">')
#print(f'    <title>{info["title"]}</title>')
print(f'    <title>{page_title}</title>')
print(f'    <style>')
print(f'      #video-controls {{')
#print(f'        position: sticky; top: 0;') # hides text when focussed with fragment ID
print(f'        position: fixed; bottom: 0;')
print(f'        background: white;')
print(f'        padding: 0.5em;')
print(f'        width: 100%;')
print(f'        border-top: solid 1px grey;')
#print(f'        text-align: center;')
print(f'      }}')
print(f'      .comment {{')
print(f'        margin: 1em 0;')
print(f'        overflow: auto;')
print(f'        word-break: break-all;')
print(f'      }}')
print(f'      .comment > details {{')
print(f'        margin-top: 1em;')
print(f'      }}')
print(f'      .comment > details > .comment {{')
#print(f'        margin: 1em 0 1em 2em;')
print(f'        margin-left: 2em;') # indent subcomments
#print(f'        padding-left: 2em;') # indent subcomments
print(f'      }}')
print(f'      .author {{')
#print(f'        display: block;')
print(f'        font-weight: bold;')
print(f'        unicode-bidi: embed;') # fix right-to-left script marker in author
print(f'      }}')
print(f'      .date {{')
print(f'        font-size: 80%;')
print(f'      }}')
print(f'      .date a {{')
print(f'        color: black;')
print(f'        text-decoration: none;')
print(f'      }}')
print(f'      .likes:before {{')
#print(f'        content: "🖒 ";') # https://emojipedia.org/reversed-thumbs-up-sign/
print(f'        content: "+";')
print(f'      }}')
# 🖓
print(f'    </style>')
print("""
    <script>
      // https://stackoverflow.com/a/45292588/10440128
      function parse_time(t) {
        return +(t.split(':').reduce((acc, val) => (60 * acc) + +val, 0));
      }
      // https://stackoverflow.com/a/10461709/10440128
      function seek(t) {
        video = document.getElementById("video");
        video.currentTime = parse_time(t);
        // TODO sleep? (wait for seek)
        video.play();
      }
    </script>
""")
print(f'  </head>')
print(f'  <body>')
#print(f'    <h1>{info["title"]}</h1>')
print(f'    <h1>{page_title}</h1>')
# TODO add sticky video controls, so i can pause when scrolled down (without "picture in picture" mode)
#     <video id="video" controls style="position: sticky; top:0;"> # too much space for video. instead, use "picture in picture" mode.
print(f'    <video id="video" controls>')
#print(f'    <video id="video" controls preload="metadata">')
# limitation: format must be one of: mp4, webm, ogg/ogv
# -> cannot be mkv

# add video

if video_path:
  print(f'      <source src="{urllib.parse.quote(video_path)}" type="video/{video_type}" />')
else:
  print(f'      <!-- no video file was found -->')

# add subtitles
for x in filter(lambda x: re.search(r"\.(srt|vtt|ass)$", x, re.I), glob.glob(base_path + ".*")):
  t = x.split(".")[-1]
  sub_lang = x.split(".")[-2]
  with open(x, "rb") as f:
    sub_data = f.read()
  sub_base64 = base64.b64encode(sub_data).decode("ascii")
  # TODO escape utf8 string for html attribute. replace "\n" with "&#10;", escape '"', etc.
  #sub_utf8 = sub_data.decode("utf8")
  default_attr = ""
  # TODO use javascript to get the system language
  # to set the correct default subtitles language
  if sub_lang == "en":
    default_attr = "default"
  print(f'      <track src="data:text/{t};base64,{sub_base64}" kind="subtitles" srclang="{sub_lang}" {default_attr} />')

print(f'    </video>')
print("""
    <script>
      globalThis.video = document.getElementById("video");
    </script>
""")
print(f'    <div id="video-controls">')
print(f'      Video:')
print(f'      <a href="javascript: video.play()">Play</a>')
print(f'      <a href="javascript: video.pause()">Pause</a>')
print(f'      <a href="javascript: video.requestPictureInPicture()">Picture In Picture</a>')
print(f'      <a href="javascript: video.muted = true">Mute</a>')
print(f'      <a href="javascript: video.muted = false">Unmute</a>')
# TODO show progress of video + click to seek
print(f'    </div>')
print(f'    <h2>Comments</h2>')
# TODO collapse/expand all subcomments
print(f'    <div class="comments">')

def render_text(text):
  # TODO render video times (more formats)
  text = re.sub(r"(?:\b|^|\n)((?:\d{1,2}:){1,2}\d{1,2})(?:\b|$|\n)", r'''<a href="javascript: seek('\1')">\1</a>''', text)
  # TODO render urls
  text = re.sub(r"(?:\b|^|\n)(https?://[a-zA-Z0-9.:/?=_+%-]+)(?:\b|$|\n)", r'<a href="\1" target="_blank">\1</a>', text)
  # TODO render hashtags
  text = re.sub(r"#([a-zA-Z0-9_]+)", r'<a href="https://www.youtube.com/hashtag/\1" target="_blank">#\1</a>', text)
  # render newlines
  text = text.replace("\n", "<br>\n")
  return text

def print_comment(comment):
  print(f'      <div class="comment" id="{comment["id"]}">')
  #print(f'        <img class=".author-{comment["author_id"]}">')
  # %T is always 00:00:00
  t = datetime.date.fromtimestamp(comment["timestamp"]).strftime("%F")
  print(f'        <div class="head">')
  print(f'          <span class="author author-{comment["author_id"]}">{comment["author"]}</span>')
  print(f'          <span class="date"><a href="#{comment["id"]}">{t}</a></span>')
  #if comment["like_count"] != 0:
  if comment.get("like_count", 0) != 0:
    print(f'          <span class="likes">{comment["like_count"]}</span>')
  #print(f'          <span class="comment-link"><a href="#{comment["id"]}">#</a>')
  print(f'        </div>')
  print(f'        <div class="body">')
  print(f'          {render_text(comment["text"])}')
  print(f'        </div>')
  if comment.get("children", []):
    print(f'        <details open>')
    print(f'        <summary></summary>')
    for subcomment_id in comment.get("children", []):
      subcomment = comment["children"][subcomment_id]
      print_comment(subcomment)
      #print(f'        <div class="subcomment">')
      #t = datetime.date.fromtimestamp(subcomment["timestamp"]).strftime("%F")
      #print(f'          <span class="author author-{subcomment["author_id"]}" title="{t}">{subcomment["author"]}</span>')
      #print(f'          {render_text(subcomment["text"])}')
      #print(f'        </div>')
    print(f'        </details>')
  print(f'      </div>')

# sort top-level comments by likes
comment_tree_items = sorted(comment_tree.items(), key=lambda item: item[1].get("like_count", 0), reverse=True)

for comment_id, comment in comment_tree_items:
  #print(comment["like_count"], "likes:", comment["text"], file=sys.stderr)
  # no, thumbs are too large. average thumb size: 8 KByte
  # this should work offline
  if False:
    thumb_path = f'youtube-author-{comment["author_id"]}.jpg'
    if not os.path.exists(thumb_path):
      print(f'fetching {thumb_path} from {comment["author_thumbnail"]}', file=sys.stderr)
      urllib.request.urlretrieve(comment["author_thumbnail"], thumb_path)
    #with urllib.request.urlopen(comment["author_thumbnail"]) as f:
    with open(thumb_path, "rb") as f:
      thumb_data = f.read()
    thumb_base64 = base64.b64encode(thumb_data)
    # https://stackoverflow.com/questions/38014918/how-to-reuse-base64-image-repeatedly-in-html-file
    print(f'      <style>')
    print(f'        .author-{comment["author_id"]} {{')
    print(f'          content: url(data:image/jpg;base64,{thumb_base64});')
    print(f'          width: 176px;')
    print(f'          height: 176px;')
    print(f'        }}')
    print(f'      </style>')
  print_comment(comment)

print(f'    </div>')
print(f'  </body>')
print(f'</html>')
```

</details>

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Out of scope. This is better off as a separate program or as a [postprocessor plugin](https://github.com/yt-dlp/yt-dlp#plugins)
