### ISSUE TITLE
Provide a Flatpak/Submit to Flathub

### ISSUE THREAD

**Issue by Throun** [yt-dlp/yt-dlp#9808]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

First off, thank you for this great project!

Atomic systems like Fedora Silverblue are commonly designed around using flatpaks as the primary, if not only, way of installing software, leaving users unable to use yt-dlp. There are some graphical programs available on Flathub that use yt-dlp, but they are limited in how much you can do compared to the command line. I believe the project should either build a flatpak or make a submission request to Flathub to allow affected users the ability to use this software.
Flatpak also helps provide a standardized environment for users; what works on one system should work exactly the same on another. This might help weed out issues that are from distros/users rather than the project.

I have written a preliminary manifest that someone can use as a start if there is interest:
[downloaders.yaml.txt](https://github.com/yt-dlp/yt-dlp/files/15140259/downloaders.yaml.txt)
[org.yt_dlp.yt_dlp.yaml.txt](https://github.com/yt-dlp/yt-dlp/files/15140260/org.yt_dlp.yt_dlp.yaml.txt)
[python3-modules.yaml.txt](https://github.com/yt-dlp/yt-dlp/files/15140261/python3-modules.yaml.txt)
I am willing to answer any questions about this to the best of my ability.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by MrRawes** [comment]
i'm running fedora silverblue, you can already run the yt-dlp release binary and flatpak isn't that well designed for gui apps

**Comment by bashonly** [comment]
This is not something I would be interested in maintaining, but I'd like to hear from the other maintainers

**Comment by Grub4K** [comment]
Why not provide the flatpak yourself?

General philosophy is that all packaging should be done third party and only the release binaries are officially maintained.

**Comment by bashonly** [comment]
from [flathub](https://flathub.org/about):

> App developers can [submit their apps](https://docs.flathub.org/docs/for-app-authors/submission) to be distributed to Flathub's growing user base, thus providing a single gateway to the entire Linux desktop ecosystem.
>
> Some apps have a checkmark on the app page under the developer name. This means the app is published on Flathub by its original developer or a third party approved by the developer.
>
> Some apps are published by third parties that are unaffiliated with the original developer. This is allowed, but such apps are not eligible for the checkmark.

If a flatpak is submitted to flathub by a third party, we will not officially approve it nor we will claim any affiliation with it, since then we would need to consistently monitor it and it would be no less work than maintaining it ourselves.

If none of the other maintainers want to take this on, then you can feel free to submit an **unofficial** flatpak.

**Comment by bashonly** [comment]
> In case you didn't see it, the manifest sources the necessary python dependencies from the [python3-modules](https://github.com/yt-dlp/yt-dlp/files/15140261/python3-modules.yaml.txt) file.

Ah, I just took a quick glance and missed that. Looking over the python3-modules, I'm noticing that the curl-cffi version included is not supported (only 0.5.10 is currently supported by yt-dlp)

**Comment by pukkandan** [comment]
For us to support a package,
1. The update process must be fully automated
2. Someone needs to be willing to maintain any future breakages

This is why we used to provide brew taps, but dropped it when the contributor in charge of maintaining it disappeared.

Since flathub [recommends manual checking before each release](https://docs.flathub.org/docs/for-app-authors/external-data-checker#automatically-merge-prs), it's probably not suitable for us to maintain.

If that is a non-issue, and you are volunteering to help us maintain it in case of future breakages, then we can support it.

Honestly, I think the needed coordination is more work than it's worth just to get marked as "official", but your choice
